"""Exact almost-cycle search on the finance-surviving frontier.

Phase 1 only: L=25781. Not a halt theorem, not a leftover-word
census, and not a 2^L enumeration. Words are generated by
run-length / mechanical constructions; closure is exact
floor-power arithmetic; even-cell branching uses the O(y^{1/3})
OE-compatible preimage, not the full even cell.

Dossier: docs/problems/juggler_cycle_almost_search.md.
"""

from __future__ import annotations

import json
import math
import os
import time
from collections import Counter
from concurrent.futures import ProcessPoolExecutor, as_completed
from math import isqrt
from typing import Any

from research.juggler_sequence.cycle_budget_opt import run_type_counts
from research.juggler_sequence.cycle_conditioned_closure import run_type_n_max
from research.juggler_sequence.cycle_finance import (
    DATA_DIR,
    PUBLISHED_FLOOR,
    o_min_and_theta,
    parity_n_max,
    sha256_int_list,
)
from research.juggler_sequence.cycle_ordered_excursion import excursion_map
from research.juggler_sequence.cycle_prefix_feasibility import (
    ceiling_christoffel_word,
    extremal_word,
    prefix_report,
)
from research.juggler_sequence.floor_preimages import odd_preimage_integers
from research.juggler_sequence.power_itineraries import floor_power

ALMOST_DIR = DATA_DIR / "almost_search"
PHASE1_L = 25781
LAB_FLOOR = 2_000_000
START = PUBLISHED_FLOOR + 1
BIT_CAP = 16_384
RESOLVE_BIT_CAP = 200_000
RESOLVE_SAMPLE = 64
PACKED_BIT_CAP = 256
BEAM = 12
FOLLOW_SAMPLE_STRIDE = 34
BACKWARD_ENDPOINTS = 48
CALIBRATION_L = 19
LONG_KEEP = 24
UNUSUAL_FACTOR = 100.0
CLOSE_ABS = 1e-8

HIST_BOUNDS = (10, 50, 100, 257, 1000, 5000, 25780, 25781)


def envelope_error(n: int, theta: float) -> float:
    """|n^P - n|/n = n^θ - 1 for P = 1+θ."""

    if n < 2 or theta <= 0.0:
        return 0.0
    return math.expm1(theta * math.log(n))


def exact_return_error(image: int, n: int) -> float:
    if n < 1:
        raise ValueError("exact_return_error requires n >= 1")
    return abs(image - n) / n


def _int_out(n: int) -> int | str:
    if n.bit_length() <= 128:
        return n
    return f"bits:{n.bit_length()}"


def cube_root_ceil(target: int) -> int:
    """Least n with n^3 >= target."""

    if target <= 0:
        return 0
    hi = 1
    while hi * hi * hi < target:
        hi *= 2
    lo = hi // 2
    while lo < hi:
        mid = (lo + hi) // 2
        if mid * mid * mid < target:
            lo = mid + 1
        else:
            hi = mid
    return lo


def odd_preimage(y: int) -> int | None:
    """Unique odd occupant of the odd cell, or None."""

    if y < 0:
        return None
    for candidate in odd_preimage_integers(y):
        if candidate % 2 == 1:
            return candidate
    return None


def compatible_oe_preimages(y: int) -> list[tuple[int, int]]:
    """Odd v with T(v) even and floor(sqrt(T(v))) = y.

    Candidates live in an interval of width O(y^{1/3}), not the
    even cell of width 2y.
    """

    if y < 1:
        return []
    lo2 = y * y
    hi2 = (y + 1) * (y + 1)
    n_lo = cube_root_ceil(lo2 * lo2)
    n_hi = cube_root_ceil(hi2 * hi2) - 1
    if n_lo % 2 == 0:
        n_lo += 1
    out: list[tuple[int, int]] = []
    for n in range(n_lo, n_hi + 1, 2):
        peak = isqrt(n * n * n)
        if peak % 2 == 0 and lo2 <= peak < hi2:
            out.append((n, peak))
    return out


def run_preimages(y: int, odd_run: int) -> list[int]:
    """Valleys v realizing O^{odd_run} E and landing at y."""

    if odd_run < 1 or y < 1:
        return []
    layer = [valley for valley, _ in compatible_oe_preimages(y)]
    for _ in range(odd_run - 1):
        nxt: list[int] = []
        for mid in layer:
            pred = odd_preimage(mid)
            if pred is not None:
                nxt.append(pred)
        layer = nxt
        if not layer:
            return []
    return layer


def circuits(word: str) -> list[tuple[int, int]]:
    """Odd/even run pairs. Requires a start-O / end-E word."""

    if not word or word[0] != "O" or word[-1] != "E":
        raise ValueError("circuits requires a start-O end-E word")
    pairs: list[tuple[int, int]] = []
    index = 0
    while index < len(word):
        odd_run = 0
        while index < len(word) and word[index] == "O":
            odd_run += 1
            index += 1
        even_run = 0
        while index < len(word) and word[index] == "E":
            even_run += 1
            index += 1
        if odd_run < 1 or even_run < 1:
            raise ValueError("circuits requires alternating O/E runs")
        pairs.append((odd_run, even_run))
    return pairs


def packed_block_word(length: int, odd: int) -> str:
    """Beatty interleaving of the finance-maximal OOE / OE blocks."""

    even = length - odd
    n_ooe, n_oe = run_type_counts(odd, even)
    total = n_ooe + n_oe
    if n_ooe * 3 + n_oe * 2 != length:
        raise ValueError("packed blocks do not sum to (L, o)")
    parts: list[str] = []
    for index in range(1, total + 1):
        is_ooe = (index * n_ooe + total - 1) // total - (
            (index - 1) * n_ooe + total - 1
        ) // total
        parts.append("OOE" if is_ooe else "OE")
    return "".join(parts)


def run_stats(word: str) -> dict[str, Any]:
    pairs = circuits(word)
    odds = [a for a, _ in pairs]
    evens = [b for _, b in pairs]
    n_ooe = sum(1 for a, b in pairs if a == 2 and b == 1)
    n_oe = sum(1 for a, b in pairs if a == 1 and b == 1)
    n_long = len(pairs) - n_ooe - n_oe
    return {
        "circuits": len(pairs),
        "a0": odds[0],
        "max_odd_run": max(odds),
        "max_even_run": max(evens),
        "n_ooe": n_ooe,
        "n_oe": n_oe,
        "n_other": n_long,
        "two_type": n_long == 0 and max(evens) == 1,
        "odd": word.count("O"),
        "even": word.count("E"),
        "length": len(word),
        "prefix": word[:32],
        "suffix": word[-32:],
    }


def distinguished_words(length: int, odd: int) -> dict[str, str]:
    return {
        "extremal": extremal_word(length),
        "christoffel": ceiling_christoffel_word(length, odd),
        "packed_block": packed_block_word(length, odd),
    }


def word_bundle(length: int, odd: int) -> dict[str, Any]:
    words = distinguished_words(length, odd)
    out: dict[str, Any] = {}
    for name, word in words.items():
        pref = prefix_report(word)
        stats = run_stats(word)
        out[name] = {
            **stats,
            "prefix_ok": pref["all_prefixes_ok"],
            "min_log_surplus": pref["min_log_surplus"],
            "min_k": pref["min_surplus_k"],
        }
    out["extremal_eq_christoffel"] = words["extremal"] == words["christoffel"]
    out["christoffel_eq_packed"] = words["christoffel"] == words["packed_block"]
    return out


def follow_word(n: int, word: str) -> dict[str, Any]:
    """Exact prefix of a prescribed word realized by T."""

    current = n
    for depth, letter in enumerate(word):
        even = current % 2 == 0
        if even != (letter == "E"):
            return {
                "depth": depth,
                "letter": letter,
                "parity": "E" if even else "O",
                "state": current,
                "complete": False,
                "image": None,
                "E": None,
            }
        current = floor_power(current)
    return {
        "depth": len(word),
        "letter": None,
        "parity": None,
        "state": current,
        "complete": True,
        "image": current,
        "E": exact_return_error(current, n),
    }


def follow_depth(n: int, word: str) -> int:
    current = n
    for depth, letter in enumerate(word):
        if (current % 2 == 0) != (letter == "E"):
            return depth
        current = floor_power(current)
    return len(word)


def backward_run_walk(
    word: str,
    endpoint: int,
    *,
    beam: int = BEAM,
) -> dict[str, Any]:
    """Exact backward beam along the run decomposition of ``word``."""

    blocks = list(reversed(circuits(word)))
    states = [endpoint]
    fail_pos = None
    fail_kind = None
    fail_block = None
    for index, (odd_run, even_run) in enumerate(blocks):
        if even_run != 1:
            fail_pos = len(blocks) - 1 - index
            fail_kind = "even_run_gt_1"
            fail_block = (odd_run, even_run)
            states = []
            break
        nxt: list[int] = []
        for y in states:
            nxt.extend(run_preimages(y, odd_run))
        if not nxt:
            fail_pos = len(blocks) - 1 - index
            fail_kind = "empty_run_preimage"
            fail_block = (odd_run, even_run)
            states = []
            break
        nxt = sorted(set(nxt))
        if len(nxt) > beam:
            nxt = nxt[: beam // 2] + nxt[-(beam - beam // 2) :]
        states = nxt
    if not states:
        return {
            "ok": False,
            "n": None,
            "E": None,
            "n_survivors": 0,
            "fail_kind": fail_kind,
            "fail_pos": fail_pos,
            "fail_block": list(fail_block) if fail_block else None,
            "blocks_done": index,
        }
    best = min(states, key=lambda n: exact_return_error(endpoint, n))
    return {
        "ok": True,
        "n": best,
        "E": exact_return_error(endpoint, best),
        "n_survivors": len(states),
        "fail_kind": None,
        "fail_pos": None,
        "fail_block": None,
        "blocks_done": len(blocks),
    }


def mitm_gap(
    n: int,
    word: str,
    *,
    beam: int = BEAM,
) -> dict[str, Any]:
    """Forward first half versus backward second half at a run split."""

    blocks = circuits(word)
    if len(blocks) < 2:
        return {"ok": False, "reason": "too_few_blocks"}
    split = len(blocks) // 2
    front = "".join("O" * a + "E" * b for a, b in blocks[:split])
    back = "".join("O" * a + "E" * b for a, b in blocks[split:])
    fwd = follow_word(n, front)
    back_walk = backward_run_walk(back, n, beam=beam)
    if not fwd["complete"] or not back_walk["ok"]:
        return {
            "ok": False,
            "follow_front": fwd["depth"],
            "front_len": len(front),
            "back_ok": back_walk["ok"],
            "back_fail": back_walk["fail_kind"],
            "gap": None,
        }
    mid_fwd = fwd["image"]
    mid_bwd = back_walk["n"]
    return {
        "ok": True,
        "follow_front": fwd["depth"],
        "front_len": len(front),
        "mid_fwd": _int_out(mid_fwd),
        "mid_bwd": _int_out(mid_bwd),
        "gap": exact_return_error(mid_fwd, mid_bwd) if mid_bwd else None,
        "back_survivors": back_walk["n_survivors"],
    }


def _hist_bucket(steps: int) -> str:
    for bound in HIST_BOUNDS:
        if steps <= bound:
            return f"le_{bound}"
    return "gt_L"


def _forward_chunk(
    start: int,
    stop: int,
    step_cap: int,
    bit_cap: int,
    target_l: int,
    target_o: int,
) -> dict[str, Any]:
    if start % 2 == 0:
        start += 1
    hist: Counter[str] = Counter()
    n_seen = 0
    drops = 0
    bit_hits = 0
    survived = 0
    o_hits = 0
    max_steps = 0
    max_bits = 0
    hardest = 0
    longest: list[tuple[int, int, int, int]] = []
    at_l: list[dict[str, Any]] = []
    bit_seeds: list[int] = []
    for n in range(start, stop + 1, 2):
        x = n
        steps = 0
        odds = 0
        local_bits = n.bit_length()
        capped = False
        while x >= n and steps < step_cap:
            if x % 2 == 1:
                odds += 1
                x = isqrt(x * x * x)
            else:
                x = isqrt(x)
            steps += 1
            bits = x.bit_length()
            if bits > local_bits:
                local_bits = bits
            if bits > bit_cap:
                bit_hits += 1
                bit_seeds.append(n)
                capped = True
                break
        n_seen += 1
        if local_bits > max_bits:
            max_bits = local_bits
        if capped:
            hist["bit_cap"] += 1
            continue
        if steps > max_steps:
            max_steps = steps
            hardest = n
        hist[_hist_bucket(steps)] += 1
        if x < n:
            drops += 1
        elif steps >= step_cap:
            survived += 1
        if steps >= target_l:
            err = exact_return_error(x, n)
            rec = {
                "n": n,
                "steps": steps,
                "odds": odds,
                "image": _int_out(x),
                "E": err,
                "o_match": odds == target_o,
                "bits": local_bits,
            }
            at_l.append(rec)
            if odds == target_o:
                o_hits += 1
        longest.append((steps, n, odds, local_bits))
        if len(longest) > LONG_KEEP * 4:
            longest.sort(reverse=True)
            longest = longest[:LONG_KEEP]
    longest.sort(reverse=True)
    longest = longest[:LONG_KEEP]
    return {
        "n_seen": n_seen,
        "drops": drops,
        "bit_hits": bit_hits,
        "survived": survived,
        "o_hits": o_hits,
        "max_steps": max_steps,
        "hardest": hardest,
        "max_bits": max_bits,
        "hist": dict(hist),
        "longest": [
            {"steps": steps, "n": n, "odds": odds, "bits": bits}
            for steps, n, odds, bits in longest
        ],
        "at_L": at_l,
        "bit_seeds": bit_seeds,
    }


def _merge_chunks(chunks: list[dict[str, Any]]) -> dict[str, Any]:
    hist: Counter[str] = Counter()
    longest: list[dict[str, Any]] = []
    at_l: list[dict[str, Any]] = []
    bit_seeds: list[int] = []
    out = {
        "n_seen": 0,
        "drops": 0,
        "bit_hits": 0,
        "survived": 0,
        "o_hits": 0,
        "max_steps": 0,
        "hardest": 0,
        "max_bits": 0,
    }
    for chunk in chunks:
        for key in ("n_seen", "drops", "bit_hits", "survived", "o_hits"):
            out[key] += chunk[key]
        hist.update(chunk["hist"])
        longest.extend(chunk["longest"])
        at_l.extend(chunk["at_L"])
        bit_seeds.extend(chunk["bit_seeds"])
        if chunk["max_bits"] > out["max_bits"]:
            out["max_bits"] = chunk["max_bits"]
        if chunk["max_steps"] > out["max_steps"]:
            out["max_steps"] = chunk["max_steps"]
            out["hardest"] = chunk["hardest"]
    longest.sort(key=lambda row: row["steps"], reverse=True)
    at_l.sort(key=lambda row: row["E"])
    out["hist"] = dict(hist)
    out["longest"] = longest[:LONG_KEEP]
    out["at_L"] = at_l[:LONG_KEEP]
    out["n_at_L"] = len(at_l)
    out["best_E_at_L"] = at_l[0]["E"] if at_l else None
    out["best_at_L"] = at_l[0] if at_l else None
    out["bit_seeds"] = bit_seeds
    return out


def forward_scan(
    lo: int,
    hi: int,
    *,
    target_l: int = PHASE1_L,
    target_o: int | None = None,
    step_cap: int | None = None,
    bit_cap: int = BIT_CAP,
    workers: int | None = None,
    chunk: int = 100_000,
) -> dict[str, Any]:
    """Exact CycleMin first-passage / length-L return scan on odds."""

    if target_o is None:
        target_o, _ = o_min_and_theta(target_l)
    if step_cap is None:
        step_cap = target_l
    if lo % 2 == 0:
        lo += 1
    worker_count = workers
    if worker_count is None:
        worker_count = max(1, (os.cpu_count() or 4) - 2)
    spans = [
        (start, min(start + chunk - 1, hi))
        for start in range(lo, hi + 1, chunk)
    ]
    started = time.perf_counter()
    if worker_count <= 1 or len(spans) <= 1:
        chunks = [
            _forward_chunk(a, b, step_cap, bit_cap, target_l, target_o)
            for a, b in spans
        ]
    else:
        chunks = []
        with ProcessPoolExecutor(max_workers=worker_count) as pool:
            futures = [
                pool.submit(
                    _forward_chunk, a, b, step_cap, bit_cap, target_l, target_o
                )
                for a, b in spans
            ]
            for future in as_completed(futures):
                chunks.append(future.result())
    merged = _merge_chunks(chunks)
    merged.update(
        {
            "lo": lo,
            "hi": hi,
            "target_L": target_l,
            "target_o": target_o,
            "step_cap": step_cap,
            "bit_cap": bit_cap,
            "workers": worker_count if len(spans) > 1 else 1,
            "elapsed_s": time.perf_counter() - started,
        }
    )
    return merged


def _resolve_chunk(
    seeds: list[int],
    step_cap: int,
    bit_cap: int,
    target_l: int,
    target_o: int,
) -> dict[str, Any]:
    hist: Counter[str] = Counter()
    unresolved: list[int] = []
    at_l: list[dict[str, Any]] = []
    longest: list[dict[str, Any]] = []
    max_steps = 0
    max_bits = 0
    hardest = 0
    drops = 0
    for n in seeds:
        x = n
        steps = 0
        odds = 0
        local_bits = n.bit_length()
        capped = False
        while x >= n and steps < step_cap:
            if x % 2 == 1:
                odds += 1
                x = isqrt(x * x * x)
            else:
                x = isqrt(x)
            steps += 1
            bits = x.bit_length()
            if bits > local_bits:
                local_bits = bits
            if bits > bit_cap:
                capped = True
                unresolved.append(n)
                break
        if local_bits > max_bits:
            max_bits = local_bits
        if steps > max_steps:
            max_steps = steps
            hardest = n
        if capped:
            hist["bit_cap"] += 1
            continue
        hist[_hist_bucket(steps)] += 1
        if x < n:
            drops += 1
        if steps >= target_l:
            at_l.append(
                {
                    "n": n,
                    "steps": steps,
                    "odds": odds,
                    "image": _int_out(x),
                    "E": exact_return_error(x, n),
                    "o_match": odds == target_o,
                    "bits": local_bits,
                }
            )
        longest.append(
            {"steps": steps, "n": n, "odds": odds, "bits": local_bits}
        )
    return {
        "drops": drops,
        "unresolved": unresolved,
        "at_L": at_l,
        "longest": longest,
        "max_steps": max_steps,
        "hardest": hardest,
        "max_bits": max_bits,
        "hist": dict(hist),
    }


def resolve_high_peaks(
    seeds: list[int],
    *,
    step_cap: int,
    bit_cap: int = RESOLVE_BIT_CAP,
    target_l: int,
    target_o: int,
    workers: int | None = None,
) -> dict[str, Any]:
    """Re-walk bit-cap seeds with the floor-verification bit budget."""

    started = time.perf_counter()
    if not seeds:
        return {
            "n_seeds": 0,
            "drops": 0,
            "unresolved": 0,
            "unresolved_sample": [],
            "n_at_L": 0,
            "best_E_at_L": None,
            "max_steps": 0,
            "hardest": 0,
            "max_bits": 0,
            "hist": {},
            "longest": [],
            "elapsed_s": 0.0,
            "bit_cap": bit_cap,
            "step_cap": step_cap,
        }
    worker_count = workers if workers is not None else max(1, (os.cpu_count() or 4) - 2)
    if worker_count <= 1 or len(seeds) < 8:
        chunks = [_resolve_chunk(seeds, step_cap, bit_cap, target_l, target_o)]
    else:
        span = max(1, (len(seeds) + worker_count - 1) // worker_count)
        parts = [seeds[i : i + span] for i in range(0, len(seeds), span)]
        with ProcessPoolExecutor(max_workers=min(worker_count, len(parts))) as pool:
            chunks = list(
                pool.map(
                    _resolve_chunk,
                    parts,
                    [step_cap] * len(parts),
                    [bit_cap] * len(parts),
                    [target_l] * len(parts),
                    [target_o] * len(parts),
                )
            )
    hist: Counter[str] = Counter()
    unresolved: list[int] = []
    at_l: list[dict[str, Any]] = []
    longest: list[dict[str, Any]] = []
    max_steps = 0
    max_bits = 0
    hardest = 0
    drops = 0
    for chunk in chunks:
        drops += chunk["drops"]
        unresolved.extend(chunk["unresolved"])
        at_l.extend(chunk["at_L"])
        longest.extend(chunk["longest"])
        hist.update(chunk["hist"])
        if chunk["max_bits"] > max_bits:
            max_bits = chunk["max_bits"]
        if chunk["max_steps"] > max_steps:
            max_steps = chunk["max_steps"]
            hardest = chunk["hardest"]
    longest.sort(key=lambda row: row["steps"], reverse=True)
    at_l.sort(key=lambda row: row["E"])
    return {
        "n_seeds": len(seeds),
        "drops": drops,
        "unresolved": len(unresolved),
        "unresolved_sample": unresolved[:20],
        "n_at_L": len(at_l),
        "best_E_at_L": at_l[0]["E"] if at_l else None,
        "max_steps": max_steps,
        "hardest": hardest,
        "max_bits": max_bits,
        "hist": dict(hist),
        "longest": longest[:LONG_KEEP],
        "elapsed_s": time.perf_counter() - started,
        "bit_cap": bit_cap,
        "step_cap": step_cap,
    }


def word_follow_scan(
    word: str,
    lo: int,
    hi: int,
    *,
    stride: int = FOLLOW_SAMPLE_STRIDE,
) -> dict[str, Any]:
    if lo % 2 == 0:
        lo += 1
    depths: list[int] = []
    fail_letter: Counter[str] = Counter()
    fail_parity: Counter[str] = Counter()
    complete = 0
    best: dict[str, Any] | None = None
    for n in range(lo, hi + 1, stride if stride % 2 == 0 else stride):
        rec = follow_word(n, word)
        depths.append(rec["depth"])
        if rec["complete"]:
            complete += 1
            if best is None or rec["E"] < best["E"]:
                best = {"n": n, "E": rec["E"], "image": _int_out(rec["image"])}
        else:
            fail_letter[rec["letter"] or "?"] += 1
            fail_parity[f"{rec['parity']}!={rec['letter']}"] += 1
    if not depths:
        return {"n": 0}
    return {
        "n": len(depths),
        "lo": lo,
        "hi": hi,
        "stride": stride,
        "min_depth": min(depths),
        "max_depth": max(depths),
        "mean_depth": sum(depths) / len(depths),
        "complete": complete,
        "best": best,
        "fail_letter": dict(fail_letter),
        "fail_parity": dict(fail_parity),
    }


def backward_scan(
    word: str,
    endpoints: list[int],
    *,
    beam: int = BEAM,
) -> dict[str, Any]:
    fails: Counter[str] = Counter()
    blocks: Counter[str] = Counter()
    complete = 0
    errors: list[dict[str, Any]] = []
    max_done = 0
    for endpoint in endpoints:
        rec = backward_run_walk(word, endpoint, beam=beam)
        max_done = max(max_done, rec["blocks_done"])
        if rec["ok"]:
            complete += 1
            errors.append(
                {
                    "t": endpoint,
                    "n": rec["n"],
                    "E": rec["E"],
                    "survivors": rec["n_survivors"],
                }
            )
        else:
            fails[rec["fail_kind"] or "dead"] += 1
            if rec["fail_block"] is not None:
                blocks[f"{rec['fail_block'][0]},{rec['fail_block'][1]}"] += 1
    errors.sort(key=lambda row: row["E"])
    return {
        "n_endpoints": len(endpoints),
        "complete": complete,
        "min_E": errors[0]["E"] if errors else None,
        "best": errors[0] if errors else None,
        "max_blocks_done": max_done,
        "n_blocks": len(circuits(word)),
        "fail_kind": dict(fails),
        "fail_block": dict(blocks),
        "errors": errors[:8],
    }


def realized_block_endpoints(
    lo: int,
    hi: int,
    *,
    stride: int = 200,
    cap: int = BACKWARD_ENDPOINTS,
) -> list[int]:
    """Landings of realized OE / OOE blocks, so the last run can invert."""

    if lo % 2 == 0:
        lo += 1
    if stride % 2 == 1:
        stride += 1
    out: list[int] = []
    for n in range(lo, hi + 1, stride):
        for odd_run in (2, 1, 3):
            rec = excursion_map(n, odd_run)
            if rec is not None:
                out.append(rec[1])
                break
        if len(out) >= cap:
            break
    return out


def endpoint_grid(lo: int, hi: int, count: int) -> list[int]:
    if count < 2:
        return [lo if lo % 2 == 1 else lo + 1]
    lo = lo if lo % 2 == 1 else lo + 1
    hi = hi if hi % 2 == 1 else hi - 1
    if hi <= lo:
        return [lo]
    out = []
    for index in range(count):
        if count == 1:
            value = lo
        else:
            value = lo + (hi - lo) * index // (count - 1)
        if value % 2 == 0:
            value += 1
        if value > hi:
            value = hi
        out.append(value)
    return sorted(set(out))


def leftover_row(
    length: int,
    *,
    min_e: float | None,
    envelope: float,
    complete_word: bool,
    survived: int,
) -> dict[str, Any]:
    unusual = bool(
        min_e is not None
        and (
            min_e == 0.0
            or min_e < CLOSE_ABS
            or (envelope > 0.0 and min_e < envelope / UNUSUAL_FACTOR)
        )
    )
    return {
        "L": length,
        "min_E": min_e,
        "envelope_E": envelope,
        "ratio_to_envelope": (min_e / envelope) if min_e is not None and envelope else None,
        "complete_prescribed": complete_word,
        "survived_L": survived,
        "unusually_close": unusual,
        "exact_cycle": bool(min_e == 0.0),
        "kills": False,
    }


def phase1_report(
    *,
    length: int = PHASE1_L,
    floor: int = PUBLISHED_FLOOR,
    forward_lo: int | None = None,
    forward_hi: int | None = None,
    follow_hi: int | None = None,
    backward_count: int = BACKWARD_ENDPOINTS,
    workers: int | None = None,
    bit_cap: int = BIT_CAP,
    beam: int = BEAM,
    include_calibration: bool = True,
) -> dict[str, Any]:
    odd, theta = o_min_and_theta(length)
    even = length - odd
    n_run = run_type_n_max(length, odd, theta)
    n_par = parity_n_max(length, odd, theta)
    start = floor + 1
    if start % 2 == 0:
        start += 1
    if forward_lo is None:
        forward_lo = max(start, LAB_FLOOR + 1)
        if forward_lo % 2 == 0:
            forward_lo += 1
    if forward_hi is None:
        forward_hi = n_run
    if follow_hi is None:
        follow_hi = min(start + 20_000, forward_hi)
    envelope = envelope_error(start, theta)
    words = distinguished_words(length, odd)
    bundle = word_bundle(length, odd)
    fwd = forward_scan(
        forward_lo,
        forward_hi,
        target_l=length,
        target_o=odd,
        bit_cap=bit_cap,
        workers=workers,
    )
    bit_seeds = list(fwd.pop("bit_seeds", []))
    sample = bit_seeds[:: max(1, len(bit_seeds) // RESOLVE_SAMPLE)][:RESOLVE_SAMPLE]
    resolved = resolve_high_peaks(
        sample,
        step_cap=min(length, 400),
        bit_cap=RESOLVE_BIT_CAP,
        target_l=length,
        target_o=odd,
        workers=workers,
    )
    resolved["n_bit_hits"] = len(bit_seeds)
    resolved["sampled"] = len(sample)
    fwd["bit_seed_sample"] = bit_seeds[:20]
    fwd["resolved"] = resolved
    if resolved["n_at_L"]:
        fwd["n_at_L"] += resolved["n_at_L"]
        if fwd["best_E_at_L"] is None or (
            resolved["best_E_at_L"] is not None
            and resolved["best_E_at_L"] < fwd["best_E_at_L"]
        ):
            fwd["best_E_at_L"] = resolved["best_E_at_L"]
    if resolved["max_steps"] > fwd["max_steps"]:
        fwd["max_steps"] = resolved["max_steps"]
        fwd["hardest"] = resolved["hardest"]
    if resolved["max_bits"] > fwd["max_bits"]:
        fwd["max_bits"] = resolved["max_bits"]
    fwd["n_bit_hits"] = len(bit_seeds)
    fwd["unresolved_high_peaks"] = len(bit_seeds) - resolved["drops"]
    fwd["sample_unresolved"] = resolved["unresolved"]
    longest_follow = {}
    for name, word in words.items():
        depths = []
        for row in fwd["longest"]:
            depths.append(follow_depth(row["n"], word))
        longest_follow[name] = {
            "n": len(depths),
            "max_depth": max(depths) if depths else 0,
            "mean_depth": (sum(depths) / len(depths)) if depths else 0.0,
        }
    follow = {
        name: word_follow_scan(word, start, follow_hi)
        for name, word in words.items()
    }
    ends = endpoint_grid(start, min(n_run, start + 5_000_000), backward_count)
    realized = realized_block_endpoints(
        start, min(start + 50_000, n_run), cap=backward_count
    )
    ends = sorted(set(ends + realized))
    back = {
        name: backward_scan(word, ends, beam=beam)
        for name, word in words.items()
    }
    mitm_n = start
    mitm = {
        name: mitm_gap(mitm_n, word, beam=beam) for name, word in words.items()
    }
    prescribed_e = [
        row["min_E"]
        for row in back.values()
        if row["min_E"] is not None
    ]
    follow_e = [
        row["best"]["E"]
        for row in follow.values()
        if row.get("best") is not None
    ]
    min_e = fwd["best_E_at_L"]
    for value in prescribed_e + follow_e:
        if min_e is None or value < min_e:
            min_e = value
    complete_word = any(row["complete"] for row in back.values()) or any(
        row["complete"] for row in follow.values()
    )
    fail_kinds = Counter()
    fail_blocks = Counter()
    for row in back.values():
        fail_kinds.update(row["fail_kind"])
        fail_blocks.update(row["fail_block"])
    common = fail_blocks.most_common(1)
    leftover = leftover_row(
        length,
        min_e=min_e,
        envelope=envelope,
        complete_word=complete_word,
        survived=fwd["survived"] + fwd["n_at_L"],
    )
    payload: dict[str, Any] = {
        "bound": "almost_search",
        "phase": 1,
        "L": length,
        "o": odd,
        "e": even,
        "theta": theta,
        "floor": floor,
        "lab_floor": LAB_FLOOR,
        "n": start,
        "n_max_run": n_run,
        "n_max_par": n_par,
        "oo_oe": list(run_type_counts(odd, even)),
        "envelope_E": envelope,
        "words": bundle,
        "forward": fwd,
        "follow": follow,
        "follow_longest": longest_follow,
        "backward": back,
        "mitm": mitm,
        "min_E": min_e,
        "common_fail_kind": dict(fail_kinds),
        "common_fail_block": dict(fail_blocks),
        "dominant_fail_block": common[0][0] if common else None,
        "leftover": leftover,
        "envelope_dominated": bool(
            min_e is None
            or (envelope > 0.0 and min_e >= envelope / UNUSUAL_FACTOR)
        ),
        "unusually_close": leftover["unusually_close"],
        "exact_cycle": leftover["exact_cycle"],
        "leftover_killer": False,
        "requires_word_enumeration": False,
        "halt_theorem": False,
        "no_cycle_all_lengths": False,
        "sha256_L": sha256_int_list([length, odd, even]),
    }
    if include_calibration and length != CALIBRATION_L:
        payload["calibration_L19"] = phase1_report(
            length=CALIBRATION_L,
            floor=12,
            forward_lo=13,
            forward_hi=4001,
            follow_hi=2001,
            backward_count=16,
            workers=1,
            bit_cap=4096,
            beam=8,
            include_calibration=False,
        )
    return payload


def write_almost_artifacts(
    payload: dict[str, Any] | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    data = payload if payload is not None else phase1_report(**kwargs)
    ALMOST_DIR.mkdir(parents=True, exist_ok=True)
    path = ALMOST_DIR / "summary.json"
    path.write_text(json.dumps(data, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    return data


def _print_report(report: dict[str, Any]) -> None:
    slim = {
        "L": report["L"],
        "o": report["o"],
        "theta": report["theta"],
        "envelope_E": report["envelope_E"],
        "min_E": report["min_E"],
        "exact_cycle": report["exact_cycle"],
        "unusually_close": report["unusually_close"],
        "envelope_dominated": report["envelope_dominated"],
        "dominant_fail_block": report["dominant_fail_block"],
        "words": {
            name: {
                "a0": row["a0"],
                "two_type": row["two_type"],
                "n_ooe": row["n_ooe"],
                "n_oe": row["n_oe"],
                "n_other": row["n_other"],
                "max_odd_run": row["max_odd_run"],
            }
            for name, row in report["words"].items()
            if isinstance(row, dict) and "a0" in row
        },
        "forward": {
            "lo": report["forward"]["lo"],
            "hi": report["forward"]["hi"],
            "n_seen": report["forward"]["n_seen"],
            "drops": report["forward"]["drops"],
            "bit_hits": report["forward"]["bit_hits"],
            "survived": report["forward"]["survived"],
            "n_at_L": report["forward"]["n_at_L"],
            "max_steps": report["forward"]["max_steps"],
            "hardest": report["forward"]["hardest"],
            "max_bits": report["forward"]["max_bits"],
            "best_E_at_L": report["forward"]["best_E_at_L"],
            "hist": report["forward"]["hist"],
            "longest": report["forward"]["longest"][:8],
            "elapsed_s": report["forward"]["elapsed_s"],
            "workers": report["forward"]["workers"],
            "n_bit_hits": report["forward"].get("n_bit_hits"),
            "unresolved_high_peaks": report["forward"].get("unresolved_high_peaks"),
            "sample_unresolved": report["forward"].get("sample_unresolved"),
            "resolved": {
                "n_seeds": (report["forward"].get("resolved") or {}).get("n_seeds"),
                "drops": (report["forward"].get("resolved") or {}).get("drops"),
                "unresolved": (report["forward"].get("resolved") or {}).get("unresolved"),
                "max_steps": (report["forward"].get("resolved") or {}).get("max_steps"),
                "max_bits": (report["forward"].get("resolved") or {}).get("max_bits"),
                "hardest": (report["forward"].get("resolved") or {}).get("hardest"),
                "hist": (report["forward"].get("resolved") or {}).get("hist"),
                "elapsed_s": (report["forward"].get("resolved") or {}).get("elapsed_s"),
            },
        },
        "follow_longest": report.get("follow_longest"),
        "follow": {
            name: {
                "max_depth": row.get("max_depth"),
                "mean_depth": row.get("mean_depth"),
                "complete": row.get("complete"),
                "best": row.get("best"),
            }
            for name, row in report["follow"].items()
        },
        "backward": {
            name: {
                "complete": row["complete"],
                "min_E": row["min_E"],
                "max_blocks_done": row["max_blocks_done"],
                "n_blocks": row["n_blocks"],
                "fail_kind": row["fail_kind"],
                "fail_block": row["fail_block"],
            }
            for name, row in report["backward"].items()
        },
        "mitm": {
            name: {"ok": row.get("ok"), "gap": row.get("gap"), "back_fail": row.get("back_fail")}
            for name, row in report["mitm"].items()
        },
    }
    if "calibration_L19" in report:
        slim["calibration_L19"] = {
            "min_E": report["calibration_L19"]["min_E"],
            "forward_max_steps": report["calibration_L19"]["forward"]["max_steps"],
            "follow_max": {
                name: row.get("max_depth")
                for name, row in report["calibration_L19"]["follow"].items()
            },
            "backward_complete": {
                name: row["complete"]
                for name, row in report["calibration_L19"]["backward"].items()
            },
        }
    print(json.dumps(slim, indent=2))


if __name__ == "__main__":
    report = write_almost_artifacts()
    _print_report(report)
