/-
  Every Lean declaration Paper C cites, with its axiom dependencies.

  `formal/Problems/JugglerFatePaper.lean` is the root.  A name being declared and its module
  being reachable from that root says nothing about the proof: a `sorry` anywhere in its
  dependency graph, or a `native_decide`, leaves the name declared, the module reachable and
  the build green while the paper's Lean column asserts something false.

  Run `lake env lean AxiomCheckPaperC.lean` from `formal/`.  Every line of the output must
  read `[propext, Classical.choice, Quot.sound]` -- Mathlib's three and nothing else.
  `AxiomCheckPaperC.expected` is the recorded output.
-/

import Problems.JugglerFatePaper

open Problems.Juggler

#print axioms BlockAverage.block_average_bound
#print axioms BlockAverage.abs_alt_sum_le
#print axioms BlockAverage.abs_psi
#print axioms BlockAverage.block_average_asymptotic
#print axioms BlockAverage.block_average_bound_two
#print axioms BlockAverage.block_average_two_bounds
#print axioms BlockAverage.card_Ico_block
#print axioms BlockAverage.oddBlock_card_ge
#print axioms BlockAverage.oddBlock_card_le
#print axioms BlockAverage.oddBlock_filter_eq
#print axioms BlockAverage.oddBlock_quarter_close
#print axioms BlockAverage.oeFiber_card_succ_diff
#print axioms BlockAverage.psi_succ
#print axioms BlockAverage.slowSum_abs_le
#print axioms BlockAverage.slowSum_eq_fibers
#print axioms BlockAverage.block_average_of_bounds
#print axioms BlockAverage.four_card_U
#print axioms BlockAverage.mem_oddBlock
#print axioms BlockAverage.mem_oeFiber_iff_cell34
#print axioms BlockAverage.U_card_eq
#print axioms BlockAverage.oddBlock_card_eq
#print axioms Certified.chernoffExponent_thirty_gt
#print axioms Certified.chernoffExponent_thirty_lt
#print axioms Certified.cylinder_bound_thirty
#print axioms Certified.e_ge
#print axioms Certified.e_le
#print axioms Certified.klDiv_half
#print axioms Certified.klHalf_ge_of
#print axioms Certified.klHalf_le_of
#print axioms Certified.klHalf_thirty_ge
#print axioms Certified.klHalf_thirty_le
#print axioms Certified.le_log_hi
#print axioms Certified.le_log_lo
#print axioms Certified.le_log_of_pow_le
#print axioms Certified.le_log_two
#print axioms Certified.le_logb_three
#print axioms Certified.le_logb_two
#print axioms Certified.log_hi_le
#print axioms Certified.log_le_of_pow_le
#print axioms Certified.log_lo_le
#print axioms Certified.log_two_le
#print axioms Certified.logb_three_le
#print axioms Certified.logb_three_pos
#print axioms Certified.logb_tilt_thirty_le
#print axioms Certified.logb_two_le
#print axioms Certified.oneSidedExponent_half
#print axioms Certified.one_sided_thirty
#print axioms Certified.pC_thirty_ge
#print axioms Certified.pC_thirty_le
#print axioms Certified.pressure_thirty
#print axioms Collapse.Icc_eq_Ico
#print axioms Collapse.abs_alt_sum_le
#print axioms Collapse.abs_windowBias_le
#print axioms Collapse.blockSum_sub_le
#print axioms Collapse.card_filter_window
#print axioms Collapse.card_window
#print axioms Collapse.collapse_bias_le
#print axioms Collapse.collapse_bias_two_step
#print axioms Collapse.evenCount_le
#print axioms Collapse.fiber_succ
#print axioms Collapse.fiber_succ_eq
#print axioms Collapse.fiber_succ_sandwich
#print axioms Collapse.iterate_succ_eq
#print axioms Collapse.le_evenCount
#print axioms Collapse.lt_sq_succ_of_floorPower_eq
#print axioms Collapse.oddPart_nonneg
#print axioms Collapse.pre_filter_even
#print axioms Collapse.sum_abs_oddPart_sub_le
#print axioms Collapse.windowBias_eq_sum
#print axioms CylinderEnergy.energy_succ
#print axioms CylinderEnergy.itinerary_succ_append
#print axioms CylinderEnergy.sum_bias_sq
#print axioms CylinderEnergy.wordCount_split
#print axioms Energy.badEnergy_le_biasEnergy
#print axioms Energy.biasEnergy_eq
#print axioms Energy.card_allWords
#print axioms Energy.energy_conj_of_contagion
#print axioms Energy.energy_implies_conjecture
#print axioms Energy.mass_violators_le
#print axioms Energy.oneSidedBoundExc_of_energy
#print axioms Energy.oneSidedShareExc_of_energy
#print axioms Energy.wordCount_cylinder
#print axioms FiberParity.Am_double_sub_le
#print axioms FiberParity.Am_step_ge
#print axioms FiberParity.Am_step_le
#print axioms FiberParity.Hlen_eq
#print axioms FiberParity.Ioc_disjoint_next
#print axioms FiberParity.arc_count_le
#print axioms FiberParity.bad_block_logMass_le
#print axioms FiberParity.bad_count_le
#print axioms FiberParity.bad_logMass_le
#print axioms FiberParity.bad_mem_arc
#print axioms FiberParity.bad_sum_dyadic_le
#print axioms FiberParity.cell_xval_even_iff
#print axioms FiberParity.cell_xval_odd_iff
#print axioms FiberParity.eps_antitone
#print axioms FiberParity.eps_div_eps_double
#print axioms FiberParity.eps_le
#print axioms FiberParity.eps_mul_cbrt
#print axioms FiberParity.eps_pos
#print axioms FiberParity.eps_pow_two_mul
#print axioms FiberParity.evenImageCount_eq
#print axioms FiberParity.evenImageCount_eq'
#print axioms FiberParity.fiber_ge_rpow
#print axioms FiberParity.fiber_lt_rpow
#print axioms FiberParity.fiber_parity_good
#print axioms FiberParity.floor_two_xval
#print axioms FiberParity.mem_oeFiber
#print axioms FiberParity.nseq_mem
#print axioms FiberParity.nseq_step_mono
#print axioms FiberParity.nseq_succ
#print axioms FiberParity.oddImageCount_eq'
#print axioms FiberParity.oeFiber_between
#print axioms FiberParity.oeFiber_card
#print axioms FiberParity.oeFiber_card_ge
#print axioms FiberParity.oeFiber_card_le
#print axioms FiberParity.oeFiber_eq_image
#print axioms FiberParity.rpow_four_thirds_succ_ge
#print axioms FiberParity.rpow_four_thirds_succ_le
#print axioms FiberParity.rpow_two_thirds_ge
#print axioms FiberParity.rpow_two_thirds_succ_le
#print axioms FiberParity.span_ge_of_step
#print axioms FiberParity.sqrt_rpow_four_thirds
#print axioms FiberParity.step_ge
#print axioms FiberParity.step_le
#print axioms FiberParity.two_rpow_neg_third_le
#print axioms FiberParity.two_rpow_third_le
#print axioms FiberParity.two_rpow_two_thirds_le
#print axioms FiberParity.two_xval
#print axioms FiberParity.upper_step_le
#print axioms FiberParity.xval_step
#print axioms FiberParity.xval_step_ge
#print axioms FiberParity.xval_step_le
#print axioms FiberParity.xval_step_mono
#print axioms LandingWindow.cell34_eq_floorPower_two
#print axioms LandingWindow.cell34_lt_iff
#print axioms LandingWindow.exact_endpoints
#print axioms LandingWindow.exact_endpoints_iterate
#print axioms LandingWindow.le_cell34_iff
#print axioms LandingWindow.lt_windowStart_iff
#print axioms LandingWindow.setOf_cell34_mem_Ico
#print axioms LandingWindow.setOf_iterate_mem_Ico
#print axioms LandingWindow.windowStart_exists
#print axioms LandingWindow.windowStart_le_iff
#print axioms LBad_count_le
#print axioms LBad_oddCount_ge
#print axioms LBad_of_envelopeBad
#print axioms LBad_of_liveTo
#print axioms Numerics.bernoulli_ge
#print axioms Numerics.bernoulli_le
#print axioms Numerics.le_rpow_iff_pow
#print axioms Numerics.lt_rpow_iff_pow
#print axioms Numerics.rpow_le_iff_pow
#print axioms Numerics.rpow_lt_iff_pow
#print axioms OneSided.LBad_of_LBad_append
#print axioms OneSided.OneSidedShare.mono
#print axioms OneSided.OneSidedShareExc.mono_err
#print axioms OneSided.badMass_le
#print axioms OneSided.badMass_le_exc
#print axioms OneSided.badMass_one_le
#print axioms OneSided.badMass_succ_le
#print axioms OneSided.badMass_succ_le_exc
#print axioms OneSided.badWeight_le_card
#print axioms OneSided.badWeight_nonneg
#print axioms OneSided.card_cylinder_zero_le
#print axioms OneSided.cylinder_split
#print axioms OneSided.exact_share_implies_conjecture
#print axioms OneSided.exc_conj_of_contagion
#print axioms OneSided.exc_implies_conjecture
#print axioms OneSided.exp_le_rpow_scale
#print axioms OneSided.implies_conjecture_of_contagion
#print axioms OneSided.klDiv_nonneg
#print axioms OneSided.main_term_eq
#print axioms OneSided.oddFailures_card_le_badMass
#print axioms OneSided.oddFailures_le_of_exc
#print axioms OneSided.oddFailures_le_of_one_sided
#print axioms OneSided.oneSidedBoundExc_of_bound
#print axioms OneSided.oneSidedBound_of_exact
#print axioms OneSided.oneSidedShareExc_of_share
#print axioms OneSided.one_sided_bound
#print axioms OneSided.one_sided_bound_exc
#print axioms OneSided.one_sided_bound_kl
#print axioms OneSided.one_sided_bound_kl_exc
#print axioms OneSided.one_sided_implies_conjecture
#print axioms OneSided.pow_le_rpow_scale
#print axioms OneSided.pow_le_rpow_scale_gen
#print axioms OneSided.sum_allWords_succ
#print axioms OneSided.sum_pow_oddCount_le
#print axioms OneSided.tail_le
#print axioms OneSided.tilt_ge_one
#print axioms OneSided.tilt_pow_ratio
#print axioms Pressure.absorb
#print axioms Pressure.noMomentum_conj_of_contagion
#print axioms Pressure.noMomentum_implies_conjecture
#print axioms Pressure.oddFailures_le_of_noMomentum
#print axioms Pressure.oddFailures_le_of_pressure
#print axioms Pressure.oddFailures_subset_live
#print axioms Pressure.pressure_conj_of_contagion
#print axioms Pressure.pressure_implies_conjecture
#print axioms Production.coef2_ge
#print axioms Production.conjecture_of_cylinder_bound
#print axioms Production.conjecture_of_tao_rate
#print axioms Production.contagion_elementary
#print axioms Production.err2_le
#print axioms Production.err2_nonneg
#print axioms Production.errors_le
#print axioms Production.errors_vanish
#print axioms Production.failures_logMass_ge
#print axioms Production.family_E
#print axioms Production.family_OE
#print axioms Production.floor_exp_ge_half
#print axioms Production.good_fiber_logMass_ge
#print axioms Production.halfLogMass_split
#print axioms Production.logMass_contagion_elementary
#print axioms Production.one_div_floor_exp_le
#print axioms Production.production_two
#print axioms Production.production_two_sum
#print axioms Production.rate2_ge
#print axioms Production.rate2_le
#print axioms Production.rate2_pos
#print axioms Production.sqrt_floor_exp
#print axioms Production.sum_Ioc_le_sum_Ioc_pred
#print axioms Production.two_le_exp
#print axioms Production.zeta2_antitone
#print axioms Production.zeta2_pos
#print axioms ShareLaw.exists_phi_sub_eq
#print axioms ShareLaw.extremeMeasure_eq_zero
#print axioms ShareLaw.extremeMeasure_piece1
#print axioms ShareLaw.extremeMeasure_piece2
#print axioms ShareLaw.extremeMeasure_piece3
#print axioms ShareLaw.extremeMeasure_piece4
#print axioms ShareLaw.integral_extremeMeasure
#print axioms ShareLaw.phiRange_le_half_iff
#print axioms ShareLaw.phi_ge_min
#print axioms ShareLaw.phi_le_chord
#print axioms ShareLaw.phi_sub_le
#print axioms ShareLaw.taylor_three_halves
#print axioms ShareLaw.xval_expansion
#print axioms ShareLaw.xval_expansion_fiber
#print axioms Sweep.card_le_cells_mul
#print axioms Sweep.stepGe_of_steps
#print axioms Sweep.stepLe_of_steps
#print axioms WindowCount.mono_of_stepGe
#print axioms WindowCount.span_ge
#print axioms WindowCount.span_le
#print axioms WindowCount.window_card_le
#print axioms WindowCount.window_card_le_nat
#print axioms Sweep.ceil_modEq_one_iff
#print axioms Sweep.ceil_modEq_zero_iff
#print axioms Sweep.ceil_two_mul_eq
#print axioms Sweep.cell_eq
#print axioms Sweep.cell_modEq_one_iff
#print axioms Sweep.cell_modEq_zero_iff
#print axioms Sweep.cell_mono
#print axioms Sweep.cell_span
#print axioms Sweep.cell_succ_le
#print axioms Sweep.colour_card_ge
#print axioms Sweep.colour_cells_ge
#print axioms Sweep.fiber_card_ge
#print axioms Sweep.fiber_card_le
#print axioms Sweep.mono
#print axioms Sweep.step_lower
#print axioms Sweep.step_upper
#print axioms Sweep.sweep_cell
#print axioms Sweep.sweep_monotone_cell
#print axioms Sweep.three_g_ge
#print axioms ancestor_backwardClosed
#print axioms backwardClosed_iterate
#print axioms card_image_ooPiece
#print axioms chernoffExponent_nonneg
#print axioms conjecture_of_cylinder_bound_of_production
#print axioms contagion_of_production_inequality
#print axioms count_le_of_meanShare
#print axioms count_le_of_meanShareOff
#print axioms count_le_of_noMomentum
#print axioms count_le_pressure
#print axioms count_oddCount_ge_le
#print axioms count_oddCount_ge_le_exp
#print axioms count_oddCount_ge_le_kl
#print axioms count_oddCount_ge_real_le
#print axioms cube_fiber_alternating
#print axioms cube_fiber_even_image
#print axioms cube_fiber_range
#print axioms cube_fiber_sqrt_even
#print axioms cube_fiber_sqrt_odd
#print axioms cycle_basin_bounded
#print axioms cycle_basin_not_escapes
#print axioms cycles_or_escapes
#print axioms cylinder_bound_implies_conjecture
#print axioms cylinder_even_root_empty
#print axioms envelopeBad_of_liveTo
#print axioms escapes_backwardClosed
#print axioms escapes_floorPower
#print axioms escapes_forwardClosed
#print axioms even_block_card
#print axioms even_block_mem
#print axioms even_cube_fiber_full
#print axioms exists_ge_three_of_backwardClosed
#print axioms exists_minimal_failure
#print axioms exists_odd_ancestor
#print axioms exists_odd_ancestor_ge_three
#print axioms fate_trichotomy
#print axioms first_letter_pieces_disjoint
#print axioms first_letter_split
#print axioms first_letter_trichotomy
#print axioms floorPower_even_block
#print axioms floorPower_odd_even_two_step_lt
#print axioms floorPower_odd_injective
#print axioms floorPower_odd_lt
#print axioms floorPower_oe_fiber
#print axioms gA_seed
#print axioms half_le_pC
#print axioms initial_depths_are_free
#print axioms iterate_le_of_envelope
#print axioms iterate_one_fixed
#print axioms juggler_count_le_of_noMomentum
#print axioms klHalf_eq
#print axioms klHalf_nonneg
#print axioms le_rpow_div_of_pow_le
#print axioms liveCount_sum_oddCount
#print axioms liveWeight_weightSplit
#print axioms live_count_le_of_pressure
#print axioms live_count_le_pressure
#print axioms live_oddCount_ge
#print axioms logMass_contagion_of_production
#print axioms logMass_ge_gA
#print axioms logMass_le_oddLogMass
#print axioms logb_two_three_le
#print axioms meanShareOff_empty
#print axioms meanShare_of_noMomentum
#print axioms mem_iff_floorPower_mem
#print axioms mem_of_envelope_floor
#print axioms minimalMember_image_odd
#print axioms minimalMember_odd
#print axioms minimal_failure_odd_odd
#print axioms nonempty_iff_odd_image_mem
#print axioms not_reachesOne_backwardClosed
#print axioms not_reachesOne_forwardClosed
#print axioms oddFailures_card_le
#print axioms oddFailures_card_le_chernoff
#print axioms oddFailures_card_le_explicit
#print axioms oddFailures_eq_empty
#print axioms oddFailures_eventually_le
#print axioms oddFailures_subset_bad_cylinders
#print axioms oddLogMass_le_of_dyadic
#print axioms oddMass_le_weightGen
#print axioms oddMass_nonneg
#print axioms odd_cube_fiber_alternating
#print axioms odd_mem_iff
#print axioms oe_fiber_disjoint
#print axioms oe_fiber_mem
#print axioms one_add_le_exp_excess
#print axioms one_le_depth
#print axioms one_lt_logb_two_three
#print axioms pC_lt_one
#print axioms periodic_iterate_mod
#print axioms periodic_of_repeat
#print axioms power_bound_word
#print axioms prod_le_mean_pow
#print axioms prod_le_mean_pow_finset
#print axioms productionCoeff_ge
#print axioms productionCoeff_nonneg
#print axioms productionRate_ge
#print axioms productionRate_le
#print axioms productionRate_le_one
#print axioms productionRate_pos
#print axioms reachesOne_backwardClosed
#print axioms reachesOne_bounded
#print axioms reachesOne_floorPower
#print axioms reachesOne_forwardClosed
#print axioms reachesOne_not_cycle_basin
#print axioms reachesOne_not_escapes
#print axioms reachesOne_of_itinerary_envelope
#print axioms reachesOne_of_lt_two_hundred_sixty_one
#print axioms recursion_lemma
#print axioms seed_constant_pos
#print axioms seed_lemma
#print axioms shellLogMass_split
#print axioms sqrt_sqrt_eq_iff
#print axioms sum_image_ooPiece
#print axioms sweep_ceil
#print axioms sweep_fract_ge_half
#print axioms sweep_fract_lt_half
#print axioms sweep_monotone_ceil
#print axioms sweep_monotone_fract_ge_half
#print axioms sweep_monotone_fract_lt_half
#print axioms sweep_monotone_rep_gt_half
#print axioms sweep_monotone_rep_le_half
#print axioms sweep_rep_gt_half
#print axioms sweep_rep_le_half
#print axioms tao_rate_iff_conjecture
#print axioms tao_rate_implies_conjecture
#print axioms tao_rate_implies_empty
#print axioms tilt_exponent_eq_kl
#print axioms tilt_value
#print axioms tiltedShare_le_one
#print axioms tower_ratio_lt_one
#print axioms tower_tolerance_half
#print axioms weightGen_le_of_meanShare
#print axioms weightGen_le_of_meanShareOff
#print axioms weightGen_le_pressure
#print axioms weightGen_le_prod
#print axioms weightGen_nonneg
#print axioms weightGen_one
#print axioms weightGen_succ_le
#print axioms weightGen_succ_le_share
#print axioms weight_markov
#print axioms zeta_antitone
#print axioms zeta_pos_49
