import Problems.Juggler.BeattyCounting
import Problems.Juggler.BeattySlopeAsymptotic

/-! Recorded dependencies of the public arbitrary-boundary counting results.
The expanded actual-count consumers are in `InterfaceCheckBeattySlope.lean`.
-/

namespace Problems.Juggler

#print axioms BeattySlope.survives_iff_strict
#print axioms BeattySlope.survivorCount_add_passageCount
#print axioms BeattySlope.survivorCount_zero
#print axioms BeattySlope.passageCount_zero
#print axioms BeattySlope.FirstPassage.exists_even_prefix
#print axioms BeattySlope.FirstPassage.length_eq_crossingDepth
#print axioms BeattySlope.survivorCount_recurrence
#print axioms BeattySlope.survivorWeight_add_passageWeight
#print axioms BeattySlope.survivorWeight_recurrence
#print axioms BeattySlope.crossingDepth_strictMono
#print axioms BeattySlope.FirstPassage.oddCount_eq_of_length_eq_crossingDepth
#print axioms BeattySlope.passageWeight_crossingDepth
#print axioms BeattySlope.passageCount_eq_weight_div
#print axioms BeattySlope.normalizedSurvivor_recurrence
#print axioms BeattySlope.normalizedSurvivor_eq_renewalCoeff
#print axioms BeattySlope.normalizedSurvivor_three_halves_bound
#print axioms BeattySlope.normalizedSurvivor_phase_limit
#print axioms BeattySlope.tiltedOddWeight_pos
#print axioms BeattySlope.tiltedBernoulliBias_eq
#print axioms BeattySlope.tiltedBernoulliBias_bounds
#print axioms BeattySlope.tiltedOddWeight_terminal_ratio
#print axioms BeattySlope.tilted_choose_step_bound
#print axioms BeattySlope.tilted_choose_shift_bound
#print axioms BeattySlope.tilted_endpoint_first_term_bounds
#print axioms BeattySlope.tiltedBase_eq
#print axioms BeattySlope.tiltedTerminalPhase_eq
#print axioms BeattySlope.tilted_first_term_phase_limit
#print axioms BeattySlope.tilted_binomial_tail_ratio_limit
#print axioms BeattySlope.tilted_endpoint_phase_limit
#print axioms BeattySlope.tiltedTerminalPhase_bound
#print axioms BeattySlope.summable_tilted_survivor
#print axioms BeattySlope.summable_tiltedSurvivorPhase_terms
#print axioms BeattySlope.tiltedSurvivorPhase_bounds
#print axioms BeattySlope.tiltedSurvivorPhase_periodic
#print axioms BeattySlope.tilted_survivor_phase_limit
#print axioms BeattySlope.tilted_survivor_phase_limit_reciprocal
#print axioms BeattySlope.criticalWordMass_pos
#print axioms BeattySlope.criticalMass_step
#print axioms BeattySlope.passageCriticalMass_nonneg
#print axioms BeattySlope.criticalWordMass_eq_exp
#print axioms BeattySlope.survivorCriticalMass_height_split
#print axioms BeattySlope.survivorCriticalMass_tendsto_zero
#print axioms BeattySlope.criticalMass_partial_sum
#print axioms BeattySlope.passageCriticalMass_hasSum
#print axioms BeattySlope.passageIndex_ge
#print axioms BeattySlope.passageJumpWeight_eq
#print axioms BeattySlope.passageCriticalMass_crossingDepth
#print axioms BeattySlope.passageCriticalMass_eq_zero_off_range
#print axioms BeattySlope.passageJumpWeight_hasSum
#print axioms BeattySlope.passageJumpWeight_zero
#print axioms BeattySlope.passageJumpWeight_nonneg
#print axioms BeattySlope.passage_jump_weights_hasSum
#print axioms BeattySlope.passage_jump_weights_hasSum_reciprocal
#print axioms BeattySlope.passageIndex_strictMono
#print axioms BeattySlope.passagePhase_mem_Ico
#print axioms BeattySlope.passageWeight_div_eq
#print axioms BeattySlope.passageJumpWeight_eq_rpow
#print axioms BeattySlope.passageProfile_eq_transfer
#print axioms BeattySlope.passageProfile_eq_transfer_reciprocal
#print axioms BeattySlope.passageProfile_monotone
#print axioms BeattySlope.passageProfile_bounds
#print axioms BeattySlope.passageProfile_endpoints
#print axioms BeattySlope.tilted_passage_phase_limit
#print axioms BeattySlope.passagePhase_pos
#print axioms BeattySlope.endpointCutoff_passageIndex
#print axioms BeattySlope.passage_phase_asymptotic
#print axioms BeattySlope.passage_normalization_identity
#print axioms BeattySlope.passage_phase_asymptotic_odd_count
#print axioms BeattySlope.passage_phase_asymptotic_reciprocal
#print axioms BeattySlope.survivorWords_logarithmic
#print axioms BeattySlope.passageWords_logarithmic
#print axioms BeattySlope.survivorCount_logarithmic
#print axioms BeattySlope.passageCount_logarithmic
#print axioms BeattySlope.endpointCount_logarithmic
#print axioms BeattySlope.logarithmic_irrational
#print axioms BeattyPhase.survivor_count_recurrence
#print axioms BeattyPhase.survivor_exponential_identity

end Problems.Juggler
