import Problems.JugglerCollatzPaper

#print axioms Problems.Juggler.CollatzPadic.orbit_bridge
#print axioms Problems.Juggler.CollatzPadic.code_eq_iff
#print axioms Problems.Juggler.CollatzPadic.code_cylinder_eq
#print axioms Problems.Juggler.CollatzPadic.code_three_cleared
#print axioms Problems.Juggler.CollatzPadic.code_three_not_integer
#print axioms Problems.Juggler.CollatzPadic.code_not_injective
#print axioms Problems.Juggler.CollatzPadic.iterate_le_of_code_eq
#print axioms Problems.Juggler.CollatzPadic.periodic_bridge
#print axioms Problems.Collatz.PreimageGrid.count_four
#print axioms Problems.Collatz.PreimageGrid.count_odd
#print axioms Problems.Collatz.PreimageGrid.count_doubled_odd
#print axioms Problems.Collatz.PreimageGrid.measure_children
#print axioms Problems.Collatz.PreimageDomain.closed_domain_for_target
#print axioms Problems.Collatz.PreimageGrowth.growth_root
#print axioms Problems.Collatz.PreimageCertificate12.density_21_25
#print axioms Problems.Collatz.PreimageCertificate12.ancestor_density_21_25
#print axioms Problems.Collatz.PreimageBalance.certificate_power_ceiling
#print axioms Problems.Collatz.PreimageBalance.rate_lt_of_rows
#print axioms Problems.Collatz.PreimageBalance.rate_lt_of_plus_rows
#print axioms Problems.Collatz.PreimageBalance.harmonic_rate_excluded
#print axioms Problems.Collatz.BackwardMass.backward_mass_counterexample
#print axioms Problems.Juggler.CollatzMoments.complete_family_moment_loss
#print axioms Problems.Juggler.PaperECompletion.code_hasSum_odd_times
#print axioms Problems.Juggler.PaperECompletion.all_frequency_limits_iff
#print axioms Problems.Juggler.PaperECompletion.ancestor_density_real
#print axioms Problems.Juggler.PaperECompletion.certificate_log_ceiling
#print axioms Problems.Juggler.PaperECompletion.full_prefix_tree_masses
#print axioms Problems.Juggler.PaperECompletion.stopping_word_masses
#print axioms Problems.Juggler.PaperEModularReturn.modular_return_of_box
#print axioms Problems.Juggler.PaperEModularReturn.runCode_den
#print axioms Problems.Juggler.PaperEModularReturn.runCode_den_gt
#print axioms Problems.Juggler.PaperEModularReturn.theorem41_of_box_recurrence
