/-
  Every Lean declaration Paper A cites, with its axiom dependencies.

  `trust_boundary --paper a` checks that a cited name is declared and that its module is
  reachable from Paper A's root, `Problems/JugglerPaper.lean`.  Neither says the declaration
  is *proved*: a `sorry` anywhere in its dependency graph, or a `native_decide`, leaves the
  name declared, the module reachable and the build green while the paper's machine-checked
  column asserts something false.

  Names are fully qualified because two modules of the layer, `FanLaw` and `DepthFourFive`,
  declare into `Juggler.*` rather than `Problems.Juggler.*`; a single `open` would silently
  miss them.

  Run `lake env lean AxiomCheckPaperA.lean` from `formal/`.  Section 1.2 of the paper claims
  one exception to kernel checking, `window_digit_scan`, so exactly the lines that depend on
  it may name a further axiom.  `AxiomCheckPaperA.expected` is the recorded output, and the
  self-audit test regenerates and diffs it rather than trusting it.
-/

import Problems.JugglerPaper
#print axioms Problems.Juggler.absorb_odd_step
#print axioms Problems.Juggler.alpha_lt_half
#print axioms Problems.Juggler.block_envelope
#print axioms Problems.Juggler.budgetedWord_eq_hugWord
#print axioms Problems.Juggler.cf_lower_prefix
#print axioms Problems.Juggler.cf_upper_prefix
#print axioms Problems.Juggler.comparison_fails_upward
#print axioms Problems.Juggler.cross_mul_pow
#print axioms Problems.Juggler.cycleMax_start_even
#print axioms Problems.Juggler.cycleMin_charge_prefix
#print axioms Problems.Juggler.cycleMin_defect_finance
#print axioms Problems.Juggler.cycleMin_defect_le_charge
#print axioms Problems.Juggler.cycleMin_defect_le_hug_charge
#print axioms Problems.Juggler.cycleMin_even_ge_sq
#print axioms Problems.Juggler.cycleMin_finance
#print axioms Problems.Juggler.cycleMin_finance_inv_sum
#print axioms Problems.Juggler.cycleMin_gap_transfer
#print axioms Problems.Juggler.cycleMin_hug_kill_criterion
#print axioms Problems.Juggler.cycleMin_iterate_ge
#print axioms Problems.Juggler.cycleMin_length_of_gap
#print axioms Problems.Juggler.cycleMin_log_envelope
#print axioms Problems.Juggler.cycleMin_log_envelope_inv
#print axioms Problems.Juggler.cycleMin_log_le_weight
#print axioms Problems.Juggler.cycleMin_not_end_odd
#print axioms Problems.Juggler.cycleMin_odds_ge_hug
#print axioms Problems.Juggler.cycleMin_prefix_odds_ge_hug
#print axioms Problems.Juggler.cycleMin_prefix_pow_le
#print axioms Problems.Juggler.cycleMin_start_odd
#print axioms Problems.Juggler.cycleMin_to_even_superquadratic
#print axioms Problems.Juggler.cycleMin_transport
#print axioms Problems.Juggler.cycle_itinerary_formally_expanding
#print axioms Problems.Juggler.cycle_itinerary_length_ge_eleven
#print axioms Problems.Juggler.cycle_last_even_interval
#print axioms Problems.Juggler.cycle_last_even_ne_odd_sq
#print axioms Problems.Juggler.cycle_trailing_evens_lt
#print axioms Problems.Juggler.denjoy_koksma_abstract
#print axioms Problems.Juggler.denjoy_koksma_blocks
#print axioms Problems.Juggler.denjoy_koksma_cellmap
#print axioms Problems.Juggler.denjoy_koksma_rotation
#print axioms Problems.Juggler.denjoy_koksma_rotation_mean
#print axioms Problems.Juggler.denjoy_koksma_unit
#print axioms Problems.Juggler.eVariationOn_add_le
#print axioms Problems.Juggler.eVariationOn_le_of_jump
#print axioms Problems.Juggler.eVariationOn_neg
#print axioms Problems.Juggler.even_finiteProgress
#print axioms Juggler.FanLaw.expansion_e4
#print axioms Juggler.FanLaw.expansion_e5
#print axioms Juggler.FanLaw.expansion_e6
#print axioms Problems.Juggler.expansion_fails_below_22
#print axioms Problems.Juggler.expansion_holds_at_22
#print axioms Juggler.FanLaw.expansion_rate_lower
#print axioms Juggler.FanLaw.expansion_rate_upper
#print axioms Juggler.FanLaw.fanLambda
#print axioms Juggler.FanLaw.fanLambda_55_pos
#print axioms Juggler.FanLaw.fanLambda_56_neg
#print axioms Juggler.FanLaw.fanLambda_affine
#print axioms Juggler.FanLaw.fanLambda_step_neg
#print axioms Juggler.FanLaw.fanLambda_strictAnti
#print axioms Juggler.FanLaw.fanLength
#print axioms Juggler.FanLaw.fanOdd
#print axioms Juggler.FanLaw.fan_endpoint
#print axioms Juggler.FanLaw.fan_frontiers
#print axioms Juggler.FanLaw.fan_past_endpoint
#print axioms Juggler.FanLaw.fan_positive_iff
#print axioms Juggler.FanLaw.fan_step_pow
#print axioms Problems.Juggler.follows_iff_itinerary
#print axioms Problems.Juggler.four_block_pe_1999
#print axioms Problems.Juggler.global_defect_append
#print axioms Problems.Juggler.global_defect_eq_zero_iff_localsTight
#print axioms Problems.Juggler.global_defect_eq_zero_implies_monochrome
#print axioms Problems.Juggler.global_defect_identity
#print axioms Problems.Juggler.greedyDigitSum_le
#print axioms Problems.Juggler.greedy_eq_ostro
#print axioms Problems.Juggler.greedy_eq_ostro_below_window
#print axioms Problems.Juggler.greedy_reconstruct_all
#print axioms Problems.Juggler.grid_cells_collide_at_eight
#print axioms Problems.Juggler.hugEvens_eq_floor
#print axioms Problems.Juggler.hugLetter_iff_floor_step
#print axioms Problems.Juggler.hugOdds
#print axioms Problems.Juggler.hugOdds_1054
#print axioms Problems.Juggler.hugOdds_eq_ceil
#print axioms Problems.Juggler.hugOdds_eq_sub_floor
#print axioms Problems.Juggler.hugOdds_lattice_base
#print axioms Problems.Juggler.hugOdds_le_of_admissible
#print axioms Problems.Juggler.hugOdds_least
#print axioms Problems.Juggler.hugOdds_pow_ge
#print axioms Problems.Juggler.hugOdds_pow_gt
#print axioms Problems.Juggler.hugOdds_pow_lt
#print axioms Problems.Juggler.hugOdds_seed
#print axioms Problems.Juggler.hugWalk_eq_fract
#print axioms Problems.Juggler.hug_charge_maximal
#print axioms Problems.Juggler.hug_charge_unique
#print axioms Problems.Juggler.image_append
#print axioms Problems.Juggler.image_eq_iterate
#print axioms Problems.Juggler.image_eq_start_defectRatio
#print axioms Problems.Juggler.image_monotone_of_follows
#print axioms Problems.Juggler.inv_sq_le_quad
#print axioms Problems.Juggler.log_floorPower_even_ge
#print axioms Problems.Juggler.log_floorPower_even_ge_sub
#print axioms Problems.Juggler.log_floorPower_odd_ge
#print axioms Problems.Juggler.log_floorPower_odd_ge_sub
#print axioms Problems.Juggler.log_le_two_log_add
#print axioms Problems.Juggler.log_step_even
#print axioms Problems.Juggler.log_step_odd
#print axioms Problems.Juggler.log_two_div_log_three_lt
#print axioms Problems.Juggler.lowerDenom_replicate_odd
#print axioms Problems.Juggler.lower_growth_word
#print axioms Problems.Juggler.lower_lt_walkTheta
#print axioms Problems.Juggler.neg_log_one_sub_le_sixth
#print axioms Problems.Juggler.no_cycleMin_gapped_three_even_ee
#print axioms Problems.Juggler.no_cycleMin_gapped_three_even_eoe
#print axioms Problems.Juggler.no_cycle_itinerary_even_count_le_three
#print axioms Problems.Juggler.no_cycle_itinerary_gapped_three_even_ee
#print axioms Problems.Juggler.no_cycle_itinerary_gapped_three_even_eoe
#print axioms Problems.Juggler.no_cycle_itinerary_length_le_seven
#print axioms Problems.Juggler.no_cycle_itinerary_length_le_six
#print axioms Problems.Juggler.no_cycle_itinerary_ooe
#print axioms Problems.Juggler.no_cycle_itinerary_ooeoooe
#print axioms Problems.Juggler.no_cycle_itinerary_oooeoe
#print axioms Problems.Juggler.no_cycle_itinerary_oooeooe
#print axioms Problems.Juggler.no_cycle_itinerary_ooooee
#print axioms Problems.Juggler.no_cycle_itinerary_ooooeoe
#print axioms Problems.Juggler.no_cycle_itinerary_oooooee
#print axioms Problems.Juggler.no_cycle_itinerary_ooooooeee
#print axioms Problems.Juggler.no_cycle_itinerary_oooooooeeee
#print axioms Problems.Juggler.no_cycle_itinerary_three_even_eee
#print axioms Problems.Juggler.no_cycle_itinerary_three_even_eeoe
#print axioms Problems.Juggler.no_cycle_itinerary_three_even_eoee
#print axioms Problems.Juggler.no_cycle_itinerary_three_even_eoeoe
#print axioms Problems.Juggler.no_cycle_itinerary_three_even_eooee
#print axioms Problems.Juggler.no_cycle_itinerary_three_even_eooeoe
#print axioms Problems.Juggler.no_cycle_itinerary_three_even_eoooee
#print axioms Problems.Juggler.no_cycle_itinerary_two_even_ee
#print axioms Problems.Juggler.no_cycle_itinerary_two_even_eoe
#print axioms Problems.Juggler.no_cycle_odd_run_append_even
#print axioms Problems.Juggler.no_finiteProgress_implies_odd_odd
#print axioms Problems.Juggler.no_follows_seven_odds_of_lt256
#print axioms Problems.Juggler.observable_window_variation_lt_two
#print axioms Problems.Juggler.oddEvenBlock
#print axioms Problems.Juggler.odd_even_finiteProgress
#print axioms Problems.Juggler.odd_excess_lt_even
#print axioms Problems.Juggler.odd_preimage_unique
#print axioms Problems.Juggler.odd_run_ge
#print axioms Problems.Juggler.odd_run_lower_growth
#print axioms Problems.Juggler.one_plus_eta_lt_succ_sq
#print axioms Problems.Juggler.oo_suffix_threshold
#print axioms Problems.Juggler.ooo_suffix_threshold
#print axioms Problems.Juggler.orbitCell
#print axioms Problems.Juggler.orbitCell_inj
#print axioms Problems.Juggler.orbit_mem_cell
#print axioms Problems.Juggler.ostroBlocks
#print axioms Problems.Juggler.ostroBlocks_length
#print axioms Problems.Juggler.ostroBlocks_snd_sum
#print axioms Problems.Juggler.ostroDigit_le
#print axioms Problems.Juggler.ostro_digitSum_le
#print axioms Problems.Juggler.ostro_sum_eq
#print axioms Problems.Juggler.packingR_step
#print axioms Problems.Juggler.packingR_step_neg
#print axioms Problems.Juggler.packing_counts
#print axioms Problems.Juggler.period_ge_22_of_even_count
#print axioms Problems.Juggler.periodicObservable
#print axioms Problems.Juggler.periodicObservable_hugWalk
#print axioms Problems.Juggler.periodic_window_variation_le
#print axioms Problems.Juggler.power_bound_contracts
#print axioms Problems.Juggler.power_bound_eq_iff_extremal
#print axioms Problems.Juggler.power_bound_word
#print axioms Problems.Juggler.reachesOne_of_all_finiteProgress
#print axioms Problems.Juggler.rotationAverage_gap
#print axioms Problems.Juggler.rotationAverage_le
#print axioms Problems.Juggler.rotationAverage_lt
#print axioms Problems.Juggler.rotation_average_le
#print axioms Problems.Juggler.rotation_average_lt
#print axioms Problems.Juggler.runCapConst_gt
#print axioms Problems.Juggler.runCapConst_lt
#print axioms Problems.Juggler.runCap_antitone
#print axioms Problems.Juggler.runCap_eq_floor
#print axioms Problems.Juggler.runCap_tuple_seven
#print axioms Problems.Juggler.runCap_tuple_three
#print axioms Problems.Juggler.runSurvivors_length
#print axioms Problems.Juggler.run_survivor_seed_F2
#print axioms Problems.Juggler.run_survivor_seed_F3
#print axioms Problems.Juggler.run_survivor_unimodular
#print axioms Problems.Juggler.square_scale_superquadratic
#print axioms Problems.Juggler.stateCharge_antitone
#print axioms Problems.Juggler.stateCharge_inj
#print axioms Problems.Juggler.stateCharge_strictAnti
#print axioms Juggler.FanLaw.step_lt_two
#print axioms Problems.Juggler.sum_eVariationOn_Icc
#print axioms Problems.Juggler.theta_block_envelope
#print axioms Problems.Juggler.theta_block_envelope_of_length
#print axioms Problems.Juggler.theta_block_envelope_window
#print axioms Problems.Juggler.theta_block_permutations
#print axioms Problems.Juggler.theta_convergent_denominators
#print axioms Problems.Juggler.theta_convergent_numerators
#print axioms Problems.Juggler.theta_convergent_quality
#print axioms Problems.Juggler.theta_convergents_coprime
#print axioms Problems.Juggler.theta_convergents_unimodular
#print axioms Problems.Juggler.theta_digitSum_le
#print axioms Problems.Juggler.theta_sandwich_lower
#print axioms Problems.Juggler.theta_sandwich_upper
#print axioms Problems.Juggler.theta_strictMono
#print axioms Problems.Juggler.theta_sum_eq
#print axioms Problems.Juggler.three_mul_lt_two_mul_of_omin
#print axioms Problems.Juggler.three_pow_step_gt_two_pow_step
#print axioms Problems.Juggler.threshold_inherits_odd_append
#print axioms Problems.Juggler.two_n_add_one_lt_rpow_three_halves
#print axioms Problems.Juggler.value_sub_mean_le_variation
#print axioms Problems.Juggler.walkTheta
#print axioms Problems.Juggler.walkTheta_lt_upper
#print axioms Juggler.FanLaw.walk_first_letter_odd
#print axioms Juggler.FanLaw.walk_second_letter_odd
#print axioms Problems.Juggler.window_digit_cap
#print axioms Problems.Juggler.window_digit_max
#print axioms Problems.Juggler.window_digit_scan
