import BTCalculus.FejerBox

/-! Dependency audit for the finite Fejer box estimate and its supporting theorems. -/

#print axioms BTCalculus.FejerKernel.continuous_dirichlet
#print axioms BTCalculus.FejerKernel.continuous_kernel
#print axioms BTCalculus.FejerKernel.kernel_nonneg
#print axioms BTCalculus.FejerKernel.integrable_kernel
#print axioms BTCalculus.FejerKernel.norm_dirichlet_le
#print axioms BTCalculus.FejerKernel.kernel_le
#print axioms BTCalculus.FejerKernel.fourier_sub
#print axioms BTCalculus.FejerKernel.kernel_expansion
#print axioms BTCalculus.FejerKernel.integral_fourier
#print axioms BTCalculus.FejerKernel.integrable_fourier
#print axioms BTCalculus.FejerKernel.integral_kernel
#print axioms BTCalculus.FejerKernel.fourier_nat
#print axioms BTCalculus.FejerKernel.dirichlet_mul_sub_one
#print axioms BTCalculus.FejerKernel.norm_dirichlet_mul_sub_one_le
#print axioms BTCalculus.FejerKernel.norm_fourier_one_sub_one
#print axioms BTCalculus.FejerKernel.chord_lower
#print axioms BTCalculus.FejerKernel.kernel_le_inv_sq
#print axioms BTCalculus.FejerKernel.fourier_neg_input
#print axioms BTCalculus.FejerKernel.kernel_neg
#print axioms BTCalculus.FejerKernel.continuous_kernel_real
#print axioms BTCalculus.FejerKernel.positive_tail_le
#print axioms BTCalculus.FejerKernel.two_sided_tail_le
#print axioms BTCalculus.FejerKernel.circle_tail_le
#print axioms BTCalculus.FejerKernel.productKernel_nonneg
#print axioms BTCalculus.FejerKernel.integrable_productKernel
#print axioms BTCalculus.FejerKernel.integral_productKernel
#print axioms BTCalculus.FejerKernel.product_tail_le
#print axioms BTCalculus.FejerArc.arc_eq_circleArc
#print axioms BTCalculus.FejerArc.arc_empty
#print axioms BTCalculus.FejerArc.measurableSet_arc
#print axioms BTCalculus.FejerArc.coe_mem_arc_iff
#print axioms BTCalculus.FejerArc.integral_arc
#print axioms BTCalculus.FejerArc.integral_arc_one
#print axioms BTCalculus.FejerArc.arcCoeff_zero
#print axioms BTCalculus.FejerArc.norm_arcCoeff_le
#print axioms BTCalculus.FejerArc.arc_full
#print axioms BTCalculus.FejerArc.small_representative
#print axioms BTCalculus.FejerArc.sub_mem_expanded
#print axioms BTCalculus.FejerArc.mem_of_sub_mem_contracted
#print axioms BTCalculus.FejerArc.smoothSet_nonneg
#print axioms BTCalculus.FejerArc.smoothSet_le_one
#print axioms BTCalculus.FejerArc.smoothSet_eq_integral
#print axioms BTCalculus.FejerArc.indicator_le_smoothSet
#print axioms BTCalculus.FejerArc.smoothSet_le_indicator
#print axioms BTCalculus.FejerArc.arc_smoothing_sandwich
#print axioms BTCalculus.FejerArc.fourier_sub_input
#print axioms BTCalculus.FejerArc.smoothSet_arc_expansion
#print axioms BTCalculus.FejerArc.norm_arcCoeff_le_weight
#print axioms BTCalculus.FejerArc.sum_frequencyWeight
#print axioms BTCalculus.FejerArc.sum_norm_arcCoeff_row
#print axioms BTCalculus.FourierDiscrepancy.average_finsetSum
#print axioms BTCalculus.FourierDiscrepancy.average_const_mul
#print axioms BTCalculus.FourierDiscrepancy.average_const
#print axioms BTCalculus.FourierDiscrepancy.indexed_average_bound
#print axioms BTCalculus.FourierDiscrepancy.polynomial_average_bound
#print axioms BTCalculus.FourierDiscrepancy.realAverage_re
#print axioms BTCalculus.FourierDiscrepancy.polynomial_real_average_bound
#print axioms BTCalculus.FourierDiscrepancy.count_sandwich
#print axioms BTCalculus.FourierDiscrepancy.count_of_polynomial_sandwich
#print axioms BTCalculus.FourierDiscrepancy.smoothing_scale
#print axioms BTCalculus.FejerBox.frequency_bound
#print axioms BTCalculus.FejerBox.smooth_expansion
#print axioms BTCalculus.FejerBox.coefficient_mass
#print axioms BTCalculus.FejerBox.coefficient_zero_sum
#print axioms BTCalculus.FejerBox.boxSmooth_expansion
#print axioms BTCalculus.FejerBox.boxSmooth_average_bound
#print axioms BTCalculus.FejerBox.product_indicator_sandwich
#print axioms BTCalculus.FejerBox.box_smoothing_sandwich
#print axioms BTCalculus.FejerBox.saturated_lengths
#print axioms BTCalculus.FejerBox.product_volume_error
#print axioms BTCalculus.FejerBox.count_density_bounds
#print axioms BTCalculus.FejerBox.finite_box_discrepancy
