import Problems.Juggler.BeattyCounting
import Problems.Juggler.BeattySlopeLocalContent
import Problems.Juggler.BeattySlopeArithmetic
import Problems.Juggler.BeattySlopeContinuity
import Problems.Juggler.BeattySlopeLiouville
import Problems.Juggler.BeattySlopeDiophantineDim
import Problems.Juggler.BeattySlopeExactDim
import Problems.Juggler.BeattySlopeIrrExp
import Problems.Juggler.BeattySlopeRegularDim
import Problems.Juggler.BeattySlopeConvergents
import Problems.Juggler.BeattySlopeCFExpansion
import Problems.Juggler.BeattySlopePacking
import Problems.Juggler.BeattySlopeMeasureDim
import Problems.Juggler.BeattySlopeStarDim
import Problems.Juggler.BeattySlopeLawPacking
import Problems.Juggler.BeattySlopeIsolated
import Problems.Juggler.BeattyIsoExact
import Problems.Juggler.BeattyTwoScaleExact
import Problems.Juggler.BeattySlopeFrostman
import Problems.Juggler.BeattySlopeRationalLimit
import Problems.Juggler.BeattySlopeGlobalLaw
import Problems.Juggler.BeattySlopeLawContinuity
import Problems.Juggler.BeattySlopeGammaContinuity
import Problems.Juggler.BeattySlopeGammaHausdorff
import Problems.Juggler.BeattySlopeGammaCDF
import Problems.Juggler.BeattySlopeGammaLp
import Problems.Juggler.BeattySlopeGammaMoments
import Problems.Juggler.BeattySlopeProfileSpecialization

/-! Recorded dependencies of the public arbitrary-boundary counting results.
The expanded actual-count consumers are in `InterfaceCheckBeattySlope.lean`,
`InterfaceCheckBeattySlopeGeometry.lean` and `InterfaceCheckBeattySlopeContent.lean`.
-/

namespace Problems.Juggler

#print axioms BeattySlope.survives_iff_strict
#print axioms BeattySlope.survivorCount_add_passageCount
#print axioms BeattySlope.survivorCount_zero
#print axioms BeattySlope.passageCount_zero
#print axioms BeattySlope.FirstPassage.exists_even_prefix
#print axioms BeattySlope.FirstPassage.length_eq_crossingDepth
#print axioms BeattySlope.survivorCount_recurrence
#print axioms BeattySlope.survivorWeight_add_passageWeight
#print axioms BeattySlope.survivorWeight_recurrence
#print axioms BeattySlope.crossingDepth_strictMono
#print axioms BeattySlope.FirstPassage.oddCount_eq_of_length_eq_crossingDepth
#print axioms BeattySlope.passageWeight_crossingDepth
#print axioms BeattySlope.passageCount_eq_weight_div
#print axioms BeattySlope.normalizedSurvivor_recurrence
#print axioms BeattySlope.normalizedSurvivor_eq_renewalCoeff
#print axioms BeattySlope.normalizedSurvivor_three_halves_bound
#print axioms BeattySlope.normalizedSurvivor_phase_limit
#print axioms BeattySlope.tiltedOddWeight_pos
#print axioms BeattySlope.tiltedBernoulliBias_eq
#print axioms BeattySlope.tiltedBernoulliBias_bounds
#print axioms BeattySlope.tiltedOddWeight_terminal_ratio
#print axioms BeattySlope.tilted_choose_step_bound
#print axioms BeattySlope.tilted_choose_shift_bound
#print axioms BeattySlope.tilted_endpoint_first_term_bounds
#print axioms BeattySlope.tiltedBase_eq
#print axioms BeattySlope.tiltedTerminalPhase_eq
#print axioms BeattySlope.tilted_first_term_phase_limit
#print axioms BeattySlope.tilted_binomial_tail_ratio_limit
#print axioms BeattySlope.tilted_endpoint_phase_limit
#print axioms BeattySlope.tiltedTerminalPhase_bound
#print axioms BeattySlope.summable_tilted_survivor
#print axioms BeattySlope.summable_tiltedSurvivorPhase_terms
#print axioms BeattySlope.tiltedSurvivorPhase_bounds
#print axioms BeattySlope.tiltedSurvivorPhase_periodic
#print axioms BeattySlope.tilted_survivor_phase_limit
#print axioms BeattySlope.tilted_survivor_phase_limit_reciprocal
#print axioms BeattySlope.criticalWordMass_pos
#print axioms BeattySlope.criticalMass_step
#print axioms BeattySlope.passageCriticalMass_nonneg
#print axioms BeattySlope.criticalWordMass_eq_exp
#print axioms BeattySlope.survivorCriticalMass_height_split
#print axioms BeattySlope.survivorCriticalMass_tendsto_zero
#print axioms BeattySlope.criticalMass_partial_sum
#print axioms BeattySlope.passageCriticalMass_hasSum
#print axioms BeattySlope.passageIndex_ge
#print axioms BeattySlope.passageJumpWeight_eq
#print axioms BeattySlope.passageCriticalMass_crossingDepth
#print axioms BeattySlope.passageCriticalMass_eq_zero_off_range
#print axioms BeattySlope.passageJumpWeight_hasSum
#print axioms BeattySlope.passageJumpWeight_zero
#print axioms BeattySlope.passageJumpWeight_nonneg
#print axioms BeattySlope.passage_jump_weights_hasSum
#print axioms BeattySlope.passage_jump_weights_hasSum_reciprocal
#print axioms BeattySlope.passageIndex_strictMono
#print axioms BeattySlope.passagePhase_mem_Ico
#print axioms BeattySlope.passageWeight_div_eq
#print axioms BeattySlope.passageJumpWeight_eq_rpow
#print axioms BeattySlope.passageProfile_eq_transfer
#print axioms BeattySlope.passageProfile_eq_transfer_reciprocal
#print axioms BeattySlope.passageProfile_monotone
#print axioms BeattySlope.passageProfile_bounds
#print axioms BeattySlope.passageProfile_endpoints
#print axioms BeattySlope.tilted_passage_phase_limit
#print axioms BeattySlope.passagePhase_pos
#print axioms BeattySlope.endpointCutoff_passageIndex
#print axioms BeattySlope.passage_phase_asymptotic
#print axioms BeattySlope.passage_normalization_identity
#print axioms BeattySlope.passage_phase_asymptotic_odd_count
#print axioms BeattySlope.passage_phase_asymptotic_reciprocal
#print axioms BeattySlope.survivorWords_logarithmic
#print axioms BeattySlope.passageWords_logarithmic
#print axioms BeattySlope.survivorCount_logarithmic
#print axioms BeattySlope.passageCount_logarithmic
#print axioms BeattySlope.endpointCount_logarithmic
#print axioms BeattySlope.logarithmic_irrational
#print axioms BeattyPhase.survivor_count_recurrence
#print axioms BeattyPhase.survivor_exponential_identity

#print axioms BeattySlope.passageCount_crossingDepth_pos
#print axioms BeattySlope.passageJumpWeight_pos
#print axioms BeattySlope.passageIndex_logarithmic
#print axioms BeattySlope.passagePhase_logarithmic
#print axioms BeattySlope.criticalWordMass_logarithmic
#print axioms BeattySlope.passageJumpWeight_logarithmic
#print axioms BeattySlope.passageProfile_logarithmic
#print axioms BeattyPhase.phase_ne_one_of_irrational
#print axioms BeattyPhase.tendsto_irrational_phase_average
#print axioms BeattyPhase.irrational_rotation_fract_pos
#print axioms BeattyPhase.irrational_rotation_recurrent
#print axioms BeattyPhase.irrational_rotation_equidistributed
#print axioms BeattySlope.passagePhase_eq_fract
#print axioms BeattySlope.passagePhase_injective
#print axioms BeattySlope.passagePhase_recurrent
#print axioms BeattySlope.passageProfile_strictMonoOn
#print axioms BeattySlope.passageClusterSet_eq_jumpRange
#print axioms BeattySlope.passageClusterSet_eq_closure_range
#print axioms BeattySlope.passageRatio_cluster_iff
#print axioms BeattySlope.isCompact_passageClusterSet
#print axioms BeattySlope.perfect_passageClusterSet
#print axioms BeattySlope.volume_passageClusterSet
#print axioms BeattySlope.interior_passageClusterSet
#print axioms BeattySlope.passage_gap_endpoints_mem
#print axioms BeattySlope.passageRatio_gap_endpoints_cluster
#print axioms BeattySlope.passageRatio_eventually_avoids_gap
#print axioms BeattySlope.passageClusterSet_nonempty
#print axioms BeattySlope.passageRatio_envelope_endpoints_cluster
#print axioms BeattySlope.passageRatio_liminf_limsup
#print axioms BeattySlope.passagePhase_equidistributed
#print axioms BeattySlope.passageProfile_ae_continuous
#print axioms BeattySlope.passageRatio_empiricalLaw_tendsto
#print axioms BeattySlope.passageLaw_singleton
#print axioms BeattySlope.passageLaw_cdf_continuous
#print axioms BeattySlope.passageLaw_compl_clusterSet
#print axioms BeattySlope.passageLaw_clusterSet
#print axioms BeattySlope.passageLaw_mutuallySingular_volume
#print axioms BeattySlope.passageLaw_Iic_profile
#print axioms BeattySlope.passageLaw_closed_gap
#print axioms BeattySlope.passageLaw_Iic_gap
#print axioms BeattySlope.passageRatio_threshold_frequency
#print axioms BeattySlope.passageRatio_profile_threshold_frequency
#print axioms BeattySlope.passageRatio_average_tendsto

#print axioms BeattySlope.passageAmplitude_pos
#print axioms BeattySlope.passageAmplitude_eq
#print axioms BeattySlope.passageAmplitude_reciprocal
#print axioms BeattySlope.passageWeight_phase_asymptotic
#print axioms BeattySlope.passageWeight_three_halves
#print axioms BeattySlope.passagePhase_shift_frequency
#print axioms BeattySlope.passageGapMoment_pos
#print axioms BeattySlope.passageWeight_two_thirds_limit
#print axioms BeattySlope.passage_gapCount_asymptotic
#print axioms BeattySlope.passageClusterSet_tube_formula
#print axioms BeattySlope.passageClusterSet_tube_bounds
#print axioms BeattySlope.passageCluster_minkowski_dim
#print axioms BeattySlope.passageGapMoment_eq_profile
#print axioms BeattySlope.passageGapMoment_eq_law_moment
#print axioms BeattySlope.passageMinkowskiContent_pos
#print axioms BeattySlope.passageCluster_minkowski_content
#print axioms BeattySlope.passageTailDensity_monotone
#print axioms BeattySlope.passageTailDensity_nonneg
#print axioms BeattySlope.passageTailWeight_summable
#print axioms BeattySlope.passageTailWeight_nonneg
#print axioms BeattySlope.passage_tail_gapCount_asymptotic
#print axioms BeattySlope.passageContentDensity_continuous
#print axioms BeattySlope.passageContentDensity_nonneg
#print axioms BeattySlope.passageContentDensity_monotone
#print axioms BeattySlope.passageLaw_ae_bounds
#print axioms BeattySlope.passageContentDensity_integrable
#print axioms BeattySlope.passageLocalContent_tail
#print axioms BeattySlope.passageLocalContent_mass
#print axioms BeattySlope.passageLocalContent_ne_zero
#print axioms BeattySlope.passageGeometricLaw_real
#print axioms BeattySlope.passageLocalContent_integral
#print axioms BeattySlope.passageGeometricLaw_integral
#print axioms BeattySlope.passage_tail_truncated_asymptotic
#print axioms BeattySlope.passageClusterSet_local_tube_tail
#print axioms BeattySlope.passageScaledTubeMeasure_real
#print axioms BeattySlope.passageScaledTubeMeasure_tendsto
#print axioms BeattySlope.passageTubeLaw_real
#print axioms BeattySlope.passageTubeLaw_integral
#print axioms BeattySlope.passageTubeLaw_tendsto
#print axioms BeattySlope.passageCluster_tube_average
#print axioms BeattySlope.passageCluster_hausdorff_ne_top
#print axioms BeattySlope.passageCluster_dimH_le
#print axioms BeattySlope.passageCdf_profile
#print axioms BeattySlope.passageCdf_gap
#print axioms BeattySlope.passageCdf_image_cluster
#print axioms BeattySlope.passageCdf_holder
#print axioms BeattySlope.passageCluster_hausdorff_pos
#print axioms BeattySlope.passageCluster_dimH_ge
#print axioms BeattySlope.passagePhase_hitting
#print axioms BeattySlope.passageCluster_hausdorff_dio
#print axioms BeattySlope.passageCluster_hausdorff_bad
#print axioms BeattySlope.passageCluster_dimH_eq
#print axioms BeattySlope.dio_const_below
#print axioms BeattySlope.dio_of_not_liouvilleWith
#print axioms BeattySlope.ae_irrational
#print axioms BeattySlope.ae_dio_family
#print axioms BeattySlope.ae_passageCluster_dimH
#print axioms BeattySlope.dio_of_quadratic
#print axioms BeattySlope.quadratic_cluster_hausdorff
#print axioms BeattySlope.golden_passageCluster_hausdorff
#print axioms BeattySlope.cmp_eventually
#print axioms BeattySlope.cmp_eventually_all
#print axioms BeattySlope.firstPassage_eventually
#print axioms BeattySlope.passageCount_eventually
#print axioms BeattySlope.passageIndex_eventually
#print axioms BeattySlope.passageJumpWeight_tendsto
#print axioms BeattySlope.scheffe_tsum
#print axioms BeattySlope.passageJumpWeight_l1
#print axioms BeattySlope.passagePhase_tendsto
#print axioms BeattySlope.passageProfile_tendsto
#print axioms BeattySlope.passageLaw_slope_tendsto
#print axioms BeattySlope.passageContent_tendsto
#print axioms BeattySlope.inv_tendsto_irrNhds
#print axioms BeattySlope.passageContent_slope_tendsto
#print axioms BeattySlope.passageLaw_slope_cont
#print axioms BeattySlope.passageGammaScale_pos
#print axioms BeattySlope.passageGamma_phase_asymptotic
#print axioms BeattySlope.passageGammaProfile_periodic
#print axioms BeattySlope.passageGamma_periodic_asymptotic
#print axioms BeattySlope.passageGamma_asymptotic_recip
#print axioms BeattySlope.passageGammaAmp_measurable
#print axioms BeattySlope.passageGammaAmp_pos
#print axioms BeattySlope.passageGammaAmp_bounds
#print axioms BeattySlope.passageProfile_ae_deriv_zero
#print axioms BeattySlope.passageGammaAmp_ae_deriv
#print axioms BeattySlope.passageGammaLaw_absCont
#print axioms BeattySlope.passageLaw_mutSingular_gamma
#print axioms BeattySlope.passageGammaLaw_clusterSet
#print axioms BeattySlope.passageGammaLaw_cdf_continuous
#print axioms BeattySlope.passageGamma_empiricalLaw
#print axioms BeattySlope.passageGamma_threshold_freq
#print axioms BeattySlope.passageGamma_average_tendsto
#print axioms BeattySlope.passageGammaDensity_measurable
#print axioms BeattySlope.passageGammaJumpLeft_pos
#print axioms BeattySlope.passageGammaJumpLeft_le_right
#print axioms BeattySlope.passageGammaLaw_occupation
#print axioms BeattySlope.passageGammaLaw_eq_sum_log
#print axioms BeattySlope.passageGammaLaw_eq_withDensity
#print axioms BeattySlope.passageGammaDensity_lintegral
#print axioms BeattySlope.passageGammaDensity_ae_lt_top
#print axioms BeattySlope.passageGammaDensity_nonpos
#print axioms BeattySlope.passage_log_jump_normalization
#print axioms BeattySlope.passageGammaJump_bounds
#print axioms BeattySlope.passageGammaLaw_ae_envelope
#print axioms BeattySlope.passageGammaLaw_integrable_rpow
#print axioms BeattySlope.passageGamma_endpoint_moment
#print axioms BeattySlope.passageGammaLaw_moment_hasSum
#print axioms BeattySlope.passageGammaAmp_tendsto_left
#print axioms BeattySlope.passageGammaAmp_lowerSemicont
#print axioms BeattySlope.passageGammaAmp_endpoints
#print axioms BeattySlope.passageGammaAmp_image_ordConn
#print axioms BeattySlope.passageGammaLaw_support_image
#print axioms BeattySlope.passageGammaLaw_support_jumps
#print axioms BeattySlope.passageGammaLaw_support_ordConn
#print axioms BeattySlope.passageGammaSupport_isCompact
#print axioms BeattySlope.passageGamma_cluster_iff_support
#print axioms BeattySlope.passageGammaJump_left_lt_right
#print axioms BeattySlope.passageGammaJump_mem_support
#print axioms BeattySlope.passageGamma_endpoints_mem
#print axioms BeattySlope.passageGammaLaw_support_eq_Icc
#print axioms BeattySlope.passageGamma_endpoints_bounds
#print axioms BeattySlope.passageGamma_cluster_iff
#print axioms BeattySlope.passageGammaLaw_Ioo_pos
#print axioms BeattySlope.passageGammaLaw_cdf_strictMono
#print axioms BeattySlope.passageGammaDensity_lsc
#print axioms BeattySlope.passageGammaDensity_top_of_tails
#print axioms BeattySlope.volume_passageGammaDensity_top
#print axioms BeattySlope.isOpen_passageGammaTail
#print axioms BeattySlope.isGδ_passageGammaBlowupSet
#print axioms BeattySlope.passageGammaTail_inter_open
#print axioms BeattySlope.closure_passageGammaBlowupSet
#print axioms BeattySlope.passageGammaBlowup_subset_top
#print axioms BeattySlope.volume_passageGammaBlowupSet
#print axioms BeattySlope.passageGammaDensity_superlevel
#print axioms BeattySlope.passageGammaDensity_no_ae_bound
#print axioms BeattySlope.passageGammaJump_length_le
#print axioms BeattySlope.passageGammaLaw_concentration
#print axioms BeattySlope.passageGammaLaw_cdf_holder
#print axioms BeattySlope.passageGammaDensity_weak_three
#print axioms BeattySlope.passageGammaDensity_envelope
#print axioms BeattySlope.passageGammaDensity_rpow_lt_top
#print axioms BeattySlope.passageGammaDensity_memLp
#print axioms BeattySlope.passageGammaCdf_not_lipschitzOn
#print axioms BeattySlope.passageGammaBlowupSet_eq_top
#print axioms BeattySlope.passageGammaDensity_top_hausdorff
#print axioms BeattySlope.passageGammaDensity_top_dimH_le
#print axioms BeattyPhase.jumpProfileRight_le_of_lt
#print axioms BeattyPhase.jumpProfile_le_right
#print axioms BeattyPhase.jumpRange_bracket
#print axioms BeattyPhase.jumpRange_eq_of_bracket
#print axioms BeattyPhase.mem_cutGaps
#print axioms BeattyPhase.exists_cutGap
#print axioms BeattyPhase.cutGap_eq_of_mem
#print axioms BeattyPhase.cutGap_eq_of_no_cut
#print axioms BeattyPhase.card_cutGaps_le
#print axioms BeattyPhase.jumpRange_subset_cuts
#print axioms BeattyPhase.jumpGap_mass_le
#print axioms BeattyPhase.jumpRange_hausdorff_zero
#print axioms BeattyPhase.dimH_eq_zero_of_hausdorff
#print axioms BeattySlope.tailMass_nonneg
#print axioms BeattySlope.chain_no_cut_between
#print axioms BeattySlope.chain_label_mem
#print axioms BeattySlope.card_earlyCuts_le
#print axioms BeattySlope.mem_earlyCuts
#print axioms BeattySlope.chain_cut_bound
#print axioms BeattySlope.tailMass_le
#print axioms BeattySlope.liouville_cluster_hausdorff
#print axioms BeattySlope.liouville_cluster_dimH
#print axioms BeattySlope.passageGammaAmp_tendsto
#print axioms BeattySlope.passageGammaLaw_slope_cont
#print axioms BeattySlope.rpow_finset_sum_le
#print axioms BeattySlope.sum_rpow_le_card_mul
#print axioms BeattySlope.sum_tsum_le_of_disjoint
#print axioms BeattySlope.chain_same_gap
#print axioms BeattySlope.chain_cut_bound_sharp
#print axioms BeattySlope.not_bad_cluster_hausdorff
#print axioms BeattySlope.cluster_hausdorff_pos_iff
#print axioms BeattySlope.dio_exponent_hausdorff
#print axioms BeattySlope.dio_exponent_dimH_le
#print axioms BeattySlope.sum_allWords_choose
#print axioms BeattySlope.survivorWeight_le_weakTail
#print axioms BeattySlope.tilted_boundary_term_le
#print axioms BeattySlope.survivorWeight_le_endpoint
#print axioms BeattySlope.tiltedEndpoint_tendsto_zero
#print axioms BeattySlope.tiltedSurvivor_tendsto_zero
#print axioms BeattySlope.critSurvival_tendsto_zero
#print axioms BeattySlope.passageCritMass_hasSum_all
#print axioms BeattySlope.passageJumpWeight_hasSum_all
#print axioms BeattySlope.passage_jump_hasSum_all
#print axioms BeattySlope.cmp_eventually_left
#print axioms BeattySlope.firstPassage_eventually_left
#print axioms BeattySlope.passageCount_eventually_left
#print axioms BeattySlope.passageIndex_eventually_left
#print axioms BeattySlope.passageJumpWeight_tendsto_left
#print axioms BeattySlope.passageJumpWeight_l1_left
#print axioms BeattySlope.passagePhase_tendsto_left
#print axioms BeattySlope.passageProfile_monotone_all
#print axioms BeattySlope.passageProfile_tendsto_left
#print axioms BeattySlope.passageLaw_tendsto_left
#print axioms BeattySlope.passagePhase_rational
#print axioms BeattySlope.passageProfile_rational_step
#print axioms BeattySlope.passageLaw_rational_eq
#print axioms BeattySlope.passageLaw_rational_left
#print axioms BeattySlope.inv_tendsto_left
#print axioms BeattySlope.passageLaw_rational_slope
#print axioms BeattySlope.passageProfile_lt_of_phase
#print axioms BeattySlope.passageProfile_rational_lt
#print axioms BeattySlope.weakEndpointWeight_nonneg
#print axioms BeattySlope.survivorWeight_weak_recurrence
#print axioms BeattySlope.weak_first_term_phase_limit
#print axioms BeattySlope.weak_endpoint_phase_limit
#print axioms BeattySlope.weakTerminalPhase_bounds
#print axioms BeattySlope.weakTerminalPhase_abs_le
#print axioms BeattySlope.weakTerminalPhase_periodic
#print axioms BeattySlope.normalizedWeakEndpoint_nonneg
#print axioms BeattySlope.survivor_eq_weak_renewal
#print axioms BeattySlope.summable_weak_survivor
#print axioms BeattySlope.summable_weak_phase_terms
#print axioms BeattySlope.weakSurvivorPhase_bounds
#print axioms BeattySlope.weakSurvivorPhase_periodic
#print axioms BeattySlope.weak_survivor_phase_limit
#print axioms BeattySlope.passageProfileRight_transfer
#print axioms BeattySlope.weak_passage_phase_limit
#print axioms BeattySlope.weakCutoff_passageIndex
#print axioms BeattySlope.passageRatio_sub_right_tendsto
#print axioms BeattySlope.integral_passageProfileLaw
#print axioms BeattySlope.passageProfileLaw_irrational
#print axioms BeattySlope.empiricalLaw_periodic_tendsto
#print axioms BeattySlope.passageProfileRight_rational
#print axioms BeattySlope.passageRatio_law_rational
#print axioms BeattySlope.passageProfileLaw_rational
#print axioms BeattySlope.passageRatio_law_tendsto
#print axioms BeattySlope.passageRatio_law_slope
#print axioms BeattySlope.exists_passageRatio_law
#print axioms BeattySlope.passageProfile_tendsto_of
#print axioms BeattySlope.passageAvg_tendsto_of
#print axioms BeattySlope.passageLaw_tendsto_of_avg
#print axioms BeattySlope.passageProfileLaw_continuousAt
#print axioms BeattySlope.passageProfileLaw_tendsto_left
#print axioms BeattySlope.cmp_eventually_right
#print axioms BeattySlope.firstPassage_eventually_right
#print axioms BeattySlope.passageCount_eventually_right
#print axioms BeattySlope.passageIndex_eventually_right
#print axioms BeattySlope.passageWeight_tendsto_right
#print axioms BeattySlope.passagePhase_tendsto_right
#print axioms BeattySlope.passage_tail_le
#print axioms BeattySlope.survivorWords_anti
#print axioms BeattySlope.passageWeightUp_hasSum_all
#print axioms BeattySlope.passageWeightUp_zero
#print axioms BeattySlope.passageWeightUp_hasSum
#print axioms BeattySlope.passageProfileUp_monotone
#print axioms BeattySlope.integral_passageLawUp
#print axioms BeattySlope.passageProfileLaw_tendsto_right
#print axioms BeattySlope.passagePhaseUp_rational
#print axioms BeattySlope.jumpProfile_step
#print axioms BeattySlope.integral_step_eq
#print axioms BeattySlope.passageProfileUp_rational_one
#print axioms BeattySlope.integral_passageLawUp_rational
#print axioms BeattySlope.passageProfileUp_rational_first
#print axioms BeattySlope.passageLawUp_one
#print axioms BeattySlope.passageProfileLaw_one
#print axioms BeattySlope.passageLawUp_ne_rational
#print axioms BeattySlope.passageProfileLaw_discont
#print axioms BeattySlope.passageProfileLaw_contAt_iff
#print axioms BeattySlope.inv_tendsto_right
#print axioms BeattySlope.passageLaw_slope_right
#print axioms BeattySlope.passageLaw_slope_rightCont
#print axioms BeattySlope.passageLaw_slope_left
#print axioms BeattySlope.passageLaw_slope_jump
#print axioms BeattySlope.passageLaw_slope_contAt_iff
#print axioms BeattySlope.passageLaw_slope_contAt
#print axioms BeattySlope.jumpGap_mass_ge
#print axioms BeattySlope.rotation_many_hits
#print axioms BeattySlope.passageCdf_sum_le
#print axioms BeattySlope.passageCdf_mass_lower
#print axioms BeattySlope.passageCdf_holder_sharp
#print axioms BeattySlope.passageCluster_dimH_ge_sharp
#print axioms BeattySlope.cluster_dimH_ge_sharp
#print axioms BeattySlope.cluster_dimH_ge_class
#print axioms BeattySlope.cluster_dimH_gt_denjoy
#print axioms BeattySlope.cluster_dimH_window
#print axioms BeattySlope.approx_of_liouvilleWith
#print axioms BeattySlope.cluster_dimH_eq_iff
#print axioms BeattySlope.log_cluster_dimH_iff
#print axioms BeattySlope.gapMass_nonneg
#print axioms BeattySlope.CellCover
#print axioms BeattySlope.cellCover_self
#print axioms BeattySlope.exists_cutGap_Icc
#print axioms BeattySlope.sum_biUnion_le_of_nonneg
#print axioms BeattySlope.cellCover_of_gaps
#print axioms BeattySlope.cellCover_hausdorff_zero
#print axioms BeattySlope.card_le_of_separated
#print axioms BeattySlope.phase_separated
#print axioms BeattySlope.block_count_le
#print axioms BeattySlope.sum_range_three_halves_le
#print axioms BeattySlope.cell_tail_le
#print axioms BeattySlope.chain_same_cell_gap
#print axioms BeattySlope.card_mid_gaps_le
#print axioms BeattySlope.gap_short_of_approx
#print axioms BeattySlope.card_range_filter_le
#print axioms BeattySlope.cell_block_count
#print axioms BeattySlope.cell_refine_step
#print axioms BeattySlope.step_cost_le
#print axioms BeattySlope.weight_const_nonneg
#print axioms BeattySlope.levelCovers_base
#print axioms BeattySlope.good_approx_sq
#print axioms BeattySlope.levelCovers_step
#print axioms BeattySlope.levelCovers_exists
#print axioms BeattySlope.regular_hausdorff_zero
#print axioms BeattySlope.regular_cluster_dimH_le
#print axioms BeattySlope.regular_cluster_dimH_le'
#print axioms BeattySlope.regular_dio_lower
#print axioms BeattySlope.regular_cluster_dimH_eq
#print axioms BeattySlope.cfDen_add_two
#print axioms BeattySlope.cfNum_add_two
#print axioms BeattySlope.cf_det
#print axioms BeattySlope.cf_det_two
#print axioms BeattySlope.cfDen_le_succ
#print axioms BeattySlope.cfDen_succ_pos
#print axioms BeattySlope.le_cfDen
#print axioms BeattySlope.cfDen_tendsto
#print axioms BeattySlope.cfConv_odd_lt
#print axioms BeattySlope.cfConv_even_lt
#print axioms BeattySlope.cfConv_odd_lt_even
#print axioms BeattySlope.cfConv_odd_lt_even'
#print axioms BeattySlope.cfConv_odd_lt_lim
#print axioms BeattySlope.cfLim_lt_conv_even
#print axioms BeattySlope.cfErr_pos
#print axioms BeattySlope.cf_sign_sq
#print axioms BeattySlope.abs_cf_err
#print axioms BeattySlope.cfErr_identity
#print axioms BeattySlope.cfErr_recurrence
#print axioms BeattySlope.cfErr_succ_le
#print axioms BeattySlope.cfErr_le
#print axioms BeattySlope.cfErr_ge
#print axioms BeattySlope.cf_best_approx
#print axioms BeattySlope.cf_goodConvergents
#print axioms BeattySlope.cfLim_gt
#print axioms BeattySlope.cfLim_irrational
#print axioms BeattySlope.expQuot_succ_ge
#print axioms BeattySlope.cfDen_expQuot
#print axioms BeattySlope.one_lt_expSlope
#print axioms BeattySlope.expSlope_irrational
#print axioms BeattySlope.expDen_growth
#print axioms BeattySlope.expSlope_good
#print axioms BeattySlope.expSlope_cluster_dimH
#print axioms BeattySlope.exists_slope_cluster_dimH
#print axioms BeattySlope.cluster_dimH_spectrum
#print axioms BeattySlope.regular_diophClass
#print axioms BeattySlope.expSlope_diophClass
#print axioms BeattySlope.gaussQuot_irrational
#print axioms BeattySlope.fract_pos_of_irrational
#print axioms BeattySlope.one_lt_gaussQuot
#print axioms BeattySlope.cfDigits_succ_ge
#print axioms BeattySlope.gaussQuot_nonneg
#print axioms BeattySlope.gaussQuot_step
#print axioms BeattySlope.cf_complete_identity
#print axioms BeattySlope.cf_expansion_err_le
#print axioms BeattySlope.cfLim_cfDigits
#print axioms BeattySlope.irrational_goodConvergents
#print axioms BeattySlope.cfDigits_den_tendsto
#print axioms BeattySlope.GoodConvergents.shift
#print axioms BeattySlope.cf_regular_dimH_eq
#print axioms BeattySlope.upperBoxDim_mono
#print axioms BeattySlope.upperBoxDim_closure
#print axioms BeattySlope.upperBoxDim_le_of_tube
#print axioms BeattySlope.le_upperBoxDim_of_tube
#print axioms BeattySlope.modUpperBoxDim_le
#print axioms BeattySlope.passageProfile_clamp
#print axioms BeattySlope.passageGap_right_le
#print axioms BeattySlope.exists_phase_window
#print axioms BeattySlope.tailDensity_gap_pos
#print axioms BeattySlope.passageCluster_local_tube
#print axioms BeattySlope.passageCluster_modUpperBoxDim
#print axioms BeattySlope.cluster_dim_gap_iff
#print axioms BeattySlope.window_mass_le
#print axioms BeattySlope.level_early_avoid
#print axioms BeattySlope.levelLeft_bounds
#print axioms BeattySlope.good_cf_level
#print axioms BeattySlope.passageCdf_image_volume_pos
#print axioms BeattySlope.passageLaw_dimH_ge
#print axioms BeattySlope.passagePhase_succ_fract
#print axioms BeattySlope.levelSet_measurable
#print axioms BeattySlope.passage_level
#print axioms BeattySlope.exists_fine_level
#print axioms BeattySlope.tsum_half_tail
#print axioms BeattySlope.passageLaw_null_set
#print axioms BeattySlope.passageLaw_cluster
#print axioms BeattySlope.lawDimH_le_of
#print axioms BeattySlope.exists_pos_le_finset
#print axioms BeattySlope.dioph_lower_of_class
#print axioms BeattySlope.passageLaw_lawDimH_le
#print axioms BeattySlope.passageLaw_lawDimH_liouville
#print axioms BeattySlope.passageLaw_lawDimH_eq
#print axioms BeattySlope.block_window_mass
#print axioms BeattySlope.star_cut_bound
#print axioms BeattySlope.starDim_quad
#print axioms BeattySlope.starDim_pos
#print axioms BeattySlope.dio_star_hausdorff
#print axioms BeattySlope.dio_star_dimH_le
#print axioms BeattySlope.le_upperBoxDim_of_tube_freq
#print axioms BeattySlope.measure_mul_le_thickening
#print axioms BeattySlope.conv_radius_identity
#print axioms BeattySlope.passageLaw_ball_le
#print axioms BeattySlope.passageLaw_upperBoxDim_ge
#print axioms BeattySlope.passageLaw_lawDimP_eq
#print axioms BeattySlope.passageLaw_dims_eq_iff
#print axioms BeattySlope.isoQuot_succ_ge
#print axioms BeattySlope.cfDen_isoQuot
#print axioms BeattySlope.one_lt_isoSlope
#print axioms BeattySlope.isoSlope_irrational
#print axioms BeattySlope.isoDen_growth
#print axioms BeattySlope.isoSlope_diophClass
#print axioms BeattySlope.isoSlope_dims
#print axioms BeattySlope.jumpRange_hausdorff_ne_zero
#print axioms BeattySlope.frostman_cdf_hausdorff
#print axioms BeattySlope.base_at_grid
#print axioms BeattySlope.IsoLevels.base_between
#print axioms BeattySlope.IsoLevels.chain_window
#print axioms BeattySlope.IsoLevels.hits_scale
#print axioms BeattySlope.IsoLevels.mass_sparse
#print axioms BeattySlope.IsoLevels.frostman_tree
#print axioms BeattySlope.IsoLevels.hausdorff_ne_zero
#print axioms BeattySlope.isoGamma_exponents
#print axioms BeattySlope.iso_dimH_ge
#print axioms BeattySlope.iso_dimH_eq
#print axioms BeattySlope.isoTower_dims
#print axioms BeattySlope.twoScale_dimH_ge
#print axioms BeattySlope.twoScale_hausdorff_zero
#print axioms BeattySlope.twoScale_iso_hausdorff_zero
#print axioms BeattySlope.twoScaleDim_props
#print axioms BeattySlope.twoScale_dimH_eq
#print axioms BeattySlope.twoScale_dims

end Problems.Juggler
