import Problems.JugglerCollatzPaper

#print axioms Problems.Juggler.CollatzPadic.orbit_bridge
#print axioms Problems.Juggler.CollatzPadic.code_eq_iff
#print axioms Problems.Juggler.CollatzPadic.code_cylinder_eq
#print axioms Problems.Juggler.CollatzPadic.code_three_cleared
#print axioms Problems.Juggler.CollatzPadic.code_three_not_integer
#print axioms Problems.Juggler.CollatzPadic.code_not_injective
#print axioms Problems.Juggler.CollatzPadic.iterate_le_of_code_eq
#print axioms Problems.Juggler.CollatzPadic.periodic_bridge
#print axioms Problems.Collatz.PreimageGrid.count_four
#print axioms Problems.Collatz.PreimageGrid.count_odd
#print axioms Problems.Collatz.PreimageGrid.count_doubled_odd
#print axioms Problems.Collatz.PreimageGrid.measure_children
#print axioms Problems.Collatz.PreimageDomain.closed_domain_for_target
#print axioms Problems.Collatz.PreimageGrowth.growth_root
#print axioms Problems.Collatz.PreimageCertificate12.density_21_25
#print axioms Problems.Collatz.PreimageCertificate12.ancestor_density_21_25
#print axioms Problems.Collatz.PreimageBalance.certificate_power_ceiling
#print axioms Problems.Collatz.PreimageBalance.rate_lt_of_rows
#print axioms Problems.Collatz.PreimageBalance.rate_lt_of_plus_rows
#print axioms Problems.Collatz.PreimageBalance.harmonic_rate_excluded
#print axioms Problems.Collatz.BackwardMass.backward_mass_counterexample
#print axioms Problems.Juggler.CollatzMoments.complete_family_moment_loss
#print axioms Problems.Juggler.PaperECompletion.code_hasSum_odd_times
#print axioms Problems.Juggler.PaperECompletion.all_frequency_limits_iff
#print axioms Problems.Juggler.PaperECompletion.ancestor_density_real
#print axioms Problems.Juggler.PaperECompletion.certificate_log_ceiling
#print axioms Problems.Juggler.PaperECompletion.full_prefix_tree_masses
#print axioms Problems.Juggler.PaperECompletion.stopping_word_masses
#print axioms Problems.Juggler.PaperEModularReturn.modular_return_of_box
#print axioms Problems.Juggler.PaperEModularReturn.runCode_den
#print axioms Problems.Juggler.PaperEModularReturn.runCode_den_gt
#print axioms Problems.Juggler.PaperERecurrence.theorem41
#print axioms Problems.Juggler.PaperERecurrence.box_recurrence
#print axioms BTCalculus.PowerBoxRecurrence.exists_ge_power_fract_box
#print axioms BTCalculus.FourierBoxRecurrence.tendsto_continuous_average
#print axioms BTCalculus.FourierBoxRecurrence.exists_ge_fract_box_of_phase
#print axioms BTCalculus.PowerPhaseAsymptotics.tendsto_distinct_noninteger_power_average
#print axioms BTCalculus.FourierBoxCounting.tendsto_fract_box_count
#print axioms BTCalculus.PowerBoxCounting.tendsto_power_fract_box_count
#print axioms BTCalculus.PowerBoxCounting.tendsto_powerStarts_card
#print axioms Problems.Juggler.PaperECorollaries.return_density
#print axioms Problems.Juggler.PaperECorollaries.return_parameter_density
#print axioms Problems.Juggler.PaperECorollaries.returnStarts_actual
#print axioms Problems.Juggler.PaperECorollaries.return_starts_asymptotic
#print axioms Problems.Juggler.PaperECorollaries.return_in_multiplicative_interval
#print axioms Problems.Juggler.PaperECorollaries.signature_density
#print axioms Problems.Juggler.PaperECorollaries.signature_parameter_density
#print axioms Problems.Juggler.PaperECorollaries.modular_return_of_signature
#print axioms Problems.Juggler.PaperECorollaries.signature_returns_infinite
#print axioms Problems.Juggler.OOEEffectiveModes.normalized_mode_bound
#print axioms BTCalculus.FejerBox.finite_box_discrepancy
#print axioms Problems.Juggler.OOEEffectiveReturn.return_parameter_iff
#print axioms Problems.Juggler.OOEEffectiveReturn.count_error
#print axioms Problems.Juggler.OOEEffectiveReturn.error_power_bound
#print axioms Problems.Juggler.OOEEffectiveReturn.count_at_witnessCutoff
#print axioms Problems.Juggler.OOEEffectiveReturn.exists_bounded_modular_return
