import Problems.Collatz.FibreDeficit

#print axioms Problems.Collatz.FibreActual.oddReturn_plus
#print axioms Problems.Collatz.FibreActual.numerator_pos
#print axioms Problems.Collatz.FibreActual.numerator_cast
#print axioms Problems.Collatz.FibreActual.numerator_even
#print axioms Problems.Collatz.FibreActual.pow_two_lower
#print axioms Problems.Collatz.FibreActual.raw_pos
#print axioms Problems.Collatz.FibreActual.raw_cast
#print axioms Problems.Collatz.FibreActual.raw_odd
#print axioms Problems.Collatz.FibreActual.child_mul
#print axioms Problems.Collatz.FibreActual.child_pos
#print axioms Problems.Collatz.FibreActual.child_odd
#print axioms Problems.Collatz.FibreActual.child_equation
#print axioms Problems.Collatz.FibreActual.valuation_of_odd_target
#print axioms Problems.Collatz.FibreActual.child_returns
#print axioms Problems.Collatz.FibreActual.oddReturn_mul
#print axioms Problems.Collatz.FibreActual.child_of_equation
#print axioms Problems.Collatz.FibreActual.predecessor_iff
#print axioms Problems.Collatz.FibreActual.child_injective
#print axioms Problems.Collatz.FibreActual.residue_congr
#print axioms Problems.Collatz.FibreActual.parent_raw_iff
#print axioms Problems.Collatz.FibreActual.parent_child_iff
#print axioms Problems.Collatz.FibreActual.row_eq_branchWeight
#print axioms Problems.Collatz.FibreActual.actualMass_predecessors
#print axioms Problems.Collatz.FibreActual.actualTerm_formula
#print axioms Problems.Collatz.FibreActual.project_residue
#print axioms Problems.Collatz.FibreMassError.scalar_denominator
#print axioms Problems.Collatz.FibreMassError.scalar_upper
#print axioms Problems.Collatz.FibreMassError.scalar_error
#print axioms Problems.Collatz.FibreMassError.quarter_coefficient
#print axioms Problems.Collatz.FibreMassError.sign_abs
#print axioms Problems.Collatz.FibreMassError.branchWeight_bounds
#print axioms Problems.Collatz.FibreMassError.actualTerm_nonneg
#print axioms Problems.Collatz.FibreMassError.actualTerm_le
#print axioms Problems.Collatz.FibreMassError.actual_summable
#print axioms Problems.Collatz.FibreMassError.row_error
#print axioms Problems.Collatz.FibreMassError.error_summable
#print axioms Problems.Collatz.FibreMassError.error_sum
#print axioms Problems.Collatz.FibreMassError.actual_mass_error
#print axioms Problems.Collatz.FibreMassError.predecessor_summable
#print axioms Problems.Collatz.FibreMassError.predecessor_mass_error
#print axioms Problems.Collatz.FibreDeficit.weight_nonneg
#print axioms Problems.Collatz.FibreDeficit.deficient_progression
#print axioms Problems.Collatz.FibreDeficit.progression_pos
#print axioms Problems.Collatz.FibreDeficit.progression_large
#print axioms Problems.Collatz.FibreDeficit.progression_odd
#print axioms Problems.Collatz.FibreDeficit.progression_residue
#print axioms Problems.Collatz.FibreDeficit.progression_injective
#print axioms Problems.Collatz.FibreDeficit.progression_affine
#print axioms Problems.Collatz.FibreDeficit.arithmetic_mass_not_summable
#print axioms Problems.Collatz.FibreDeficit.progression_mass_not_summable
#print axioms Problems.Collatz.FibreDeficit.residue_unit
#print axioms Problems.Collatz.FibreDeficit.deficient_mass_not_summable
#print axioms Problems.Collatz.FibreDeficit.outside_finite_mass
#print axioms Problems.Collatz.FibreDeficit.exists_predecessor_mass_lt
