"""Source-level Lean hygiene diagnostics, independent of generated inventories.

References are lexical evidence, not an elaborated dependency graph. Exact
qualified identifiers and unambiguous relative identifiers are credited;
ambiguous suffixes are reported rather than assigned to every declaration.
"""
from __future__ import annotations

from collections import defaultdict
import os
from pathlib import Path
import re


SCAN_SKIP = {".lake", "node_modules", ".git", "dist", "__pycache__", ".pytest_cache", ".venv"}
SCAN_SUFFIXES = {".lean", ".md", ".ts", ".tsx", ".py"}
# This document is generated by formalpedia from its declaration inventory.
GENERATED_REFERENCE_FILES = {"docs/research/formalpedia_decl_review.md"}
ANSI = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
STATUS = re.compile(r"^\s*(?:[^\w\s\[]+\s*)?\[\d+/\d+\]\s+(Built|Replayed)\s+([A-Za-z0-9_.]+)(?:\s|$)")
LOCATION_WARNING = re.compile(r"^\s*warning:\s+(.+?\.lean):(\d+):(\d+):\s*(.*)$")
TRAILING_WARNING = re.compile(r"^\s*(.+?\.lean):(\d+):(\d+):\s*warning:\s*(.*)$")
WARNING = re.compile(r"^\s*warning:\s*(.*)$")
NEW_COMMAND = re.compile(r"^(?:#\w+|example\b|open\b|variable\b|include\b|omit\b|attribute\b|export\b)")


def juggler_module(name: str) -> bool:
    return name == "Problems.Juggler" or name.startswith("Problems.Juggler.")


def warning_module(name: str) -> bool:
    return juggler_module(name) or name == "Problems.JugglerPaper"


def module_from_path(path: str) -> str | None:
    normalized = path.replace("\\", "/")
    parts = normalized.split("/")
    if ".lake" in parts:
        return None
    try:
        start = parts.index("Problems")
    except ValueError:
        return None
    return ".".join(parts[start:]).removesuffix(".lean")


def parse_build_output(output: str) -> dict:
    """Count scoped warning records, including diagnostics replayed from cache.

    Callers must merge stdout/stderr in order when invoking Lake. A warning
    with a source location is scoped by that location, never by a preceding
    unrelated dependency status. Unlocated warnings require a module record.
    """
    modules, warnings, unlocated = [], [], []
    current = None
    for raw in output.splitlines():
        line = ANSI.sub("", raw)
        status = STATUS.search(line)
        if status:
            current = status[2]
            if warning_module(current):
                modules.append({"status": status[1], "module": current})
            continue
        located = LOCATION_WARNING.match(line) or TRAILING_WARNING.match(line)
        if located:
            path, row, column, message = located.groups()
            module = module_from_path(path)
            if module is not None and warning_module(module):
                warnings.append({"module": module, "path": path, "line": int(row),
                                 "column": int(column), "message": message})
            continue
        warning = WARNING.match(line)
        if warning:
            if current is not None and warning_module(current):
                warnings.append({"module": current, "path": None, "line": None,
                                 "column": None, "message": warning[1]})
            elif current is None:
                unlocated.append(warning[1])
    return {"modules": modules, "warnings": warnings, "unlocated": unlocated,
            "has_scoped_evidence": bool(modules or warnings)}


def source_files(root: Path):
    """Prune dependency/build directories before descent, rather than reading them."""
    for folder, directories, files in os.walk(root):
        directories[:] = sorted(d for d in directories if d not in SCAN_SKIP)
        for name in sorted(files):
            path = Path(folder) / name
            if (path.suffix in SCAN_SUFFIXES
                    and path.relative_to(root).as_posix() not in GENERATED_REFERENCE_FILES):
                yield path


def orphan_report(root: Path, trust) -> dict:
    """Live public qualified candidates and identifier-aware reference evidence.

    Declaration headers and recursive self-references are not consumers.
    Structure fields are not explicit source declarations in this inventory.
    This intentionally does not infer every `open`/type-directed resolution;
    ambiguous source tokens remain visible for review rather than silently
    making all same-basename declarations appear used.
    """
    index = trust.declaration_index()
    candidates = {full: rows for full, rows in index.items()
                  if any(juggler_module(str(row["module_name"])) for row in rows)}
    aliases = defaultdict(set)
    namespaces = set()
    for full in index:
        parts = full.split(".")
        for start in range(len(parts)):
            aliases[".".join(parts[start:])].add(full)
        for end in range(1, len(parts)):
            namespaces.add(".".join(parts[:end]))
    declared_at = defaultdict(dict)
    for full, rows in index.items():
        for row in rows:
            path = "formal/" + str(row["module_name"]).replace(".", "/") + ".lean"
            declared_at[path][int(row["line"])] = full
    references = defaultdict(list)
    ambiguous = defaultdict(set)

    def resolve(token, namespace):
        if token.startswith("_root_."):
            return {token.removeprefix("_root_.")} & index.keys()
        if token.startswith("Problems."):
            return {token} & index.keys()
        if namespace is not None:
            parts = namespace.split(".") if namespace else []
            for end in range(len(parts), -1, -1):
                full = ".".join(parts[:end] + [token])
                if full in index:
                    return {full}
        matches = aliases.get(token, set())
        if not matches and "." in token:
            # An object-method token can name a uniquely identified method;
            # never drop a known namespace qualifier or an ambiguous suffix.
            head, tail = token.rsplit(".", 1)
            if head not in namespaces and head not in aliases:
                matches = aliases.get(tail, set())
        return matches

    for path in source_files(root):
        relative = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        if path.suffix == ".lean":
            commands = trust.scoped_source_commands(text)
        else:
            commands = [(line, command, None, False) for line, command in enumerate(text.splitlines(), 1)]
        owner, previous_namespace, private_self = None, None, set()
        for line, command, namespace, private_scope in commands:
            if namespace != previous_namespace:
                owner, private_self = None, set()
            previous_namespace = namespace
            if path.suffix == ".lean":
                command = command.strip()
                declaration = trust.DECL.match(command)
                if declaration:
                    owner = declared_at[relative].get(line)
                    name = declaration["name"]
                    private_self = ({name, ".".join(filter(None, [namespace, name]))}
                                    if private_scope or "private" in declaration["modifiers"].split()
                                    else set())
                    # A declaration header is never a use, including private
                    # names that are deliberately absent from the public index.
                    start, end = declaration.span("name")
                    command = command[:start] + " " * (end - start) + command[end:]
                elif NEW_COMMAND.match(command):
                    owner, private_self = None, set()
            for token in trust.identifier_tokens(command):
                if token in private_self:
                    continue
                matches = resolve(token, namespace)
                if len(matches) > 1:
                    ambiguous[token].update(matches & candidates.keys())
                elif len(matches) == 1:
                    full = next(iter(matches))
                    if full in candidates and full != owner:
                        if len(references[full]) < 3:
                            references[full].append({"path": relative, "line": line, "token": token})
    orphans = [{"qualified_name": full, "locations": candidates[full]}
               for full in sorted(candidates) if not references[full]]
    return {"candidate_count": len(candidates), "orphans": orphans,
            "references": dict(references),
            "ambiguous_tokens": {token: sorted(names) for token, names in sorted(ambiguous.items()) if names}}
