"""Index and validate the current preprints and their publication kits.

Run --write-index after changing a paper's metadata; --check also validates
every release manifest, PDF alias, source archive and kit checksum.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LETTERS = "abcde"
KIT_FILES = {
    "a": ("README.md", "AFTER_ZENODO.md", "SOURCE_README.md", "ZENODO_FIELDS.txt",
          "SHA256SUMS.txt", "paper_a_publication_check.json",
          "paper_a_source_and_verification.zip", "paper_a_zenodo_package.zip"),
    "b": ("README.md", "AFTER_ZENODO.md", "ZENODO_FIELDS.txt", "SHA256SUMS.txt",
          "paper_b_release_check.json", "paper_b_source_package.zip", "paper_b_zenodo_package.zip"),
    "c": ("README.md", "AFTER_ZENODO.md", "ZENODO_FIELDS.txt"),
    "d": ("README.md", "AFTER_ZENODO.md", "ZENODO_FIELDS.txt", "SHA256SUMS.txt"),
    "e": ("README.md", "SOURCE_README.md", "ZENODO_FIELDS.txt", "SHA256SUMS.txt",
          "Sources_and_certificate.zip"),
}


def builder(root: Path, letter: str):
    spec = importlib.util.spec_from_file_location(
        f"preprints_{letter}", root / f"tools/build_paper_{letter}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def expected_files(root: Path) -> set[str]:
    names = {"README.md"}
    for letter in LETTERS:
        module = builder(root, letter)
        # Paper B also supports compilation from a standalone source archive.
        pdf = f"preprints/{module.STEM}.pdf" if letter == "b" else module.PDF
        exports = module.EXPORTS if letter == "b" else module.export_pairs(root)
        names.add(str(Path(pdf).relative_to("preprints")).replace("\\", "/"))
        names.update(Path(target).relative_to("preprints").as_posix() for _, target in exports)
        names.update(f"zenodo_paper_{letter}/{name}" for name in KIT_FILES[letter])
    return names


def index_text(root: Path) -> str:
    lines = [
        "# Preprints", "",
        "Current local papers of the Juggler–Collatz Mathematical Laboratory.",
        "Manuscripts, proof reviews and build instructions live in `docs/theory/`.",
        "This directory holds built PDFs and the files needed to prepare their publication.",
        "Local versions may be ahead of the [recorded deposits](../docs/theory/paper_deposits.md).",
        "A successful build does not publish anything or change a paper's evidence status.", "",
        "<!-- Generated by python tools/preprints.py --write-index. -->", "",
        "| Paper | Local version | PDF | Canonical source | Build guide | Publication kit |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for letter in LETTERS:
        module = builder(root, letter)
        meta = json.loads((root / module.METADATA).read_text(encoding="utf-8"))
        meta = meta.get("metadata", meta)
        stem = module.STEM
        title = meta["title"].replace("|", "\\|")
        lines.append(f"| {letter.upper()} | {meta['version']} | [{title}]({stem}.pdf) | "
                     f"[Manuscript](../docs/theory/{stem}.md) | "
                     f"[Build](../docs/theory/PAPER_{letter.upper()}_BUILD.md) | "
                     f"[Files and instructions](zenodo_paper_{letter}/README.md) |")
    lines += ["", "## Keeping this directory current", "",
              "Run these commands from the repository root:", "", "```text",
              "python tools/preprints.py --write-index",
              "python tools/preprints.py --check", "```", "",
              "The check rejects missing or unowned files, an outdated index, stale release inputs,",
              "mismatched PDF aliases, and stale archives or checksums. Rebuild an affected paper",
              "using its build guide; never repair a release by editing recorded hashes.", "",
              "Each kit keeps its established upload filename as an exact alias of the top-level PDF.",
              "`ZENODO_FIELDS.txt` supplies the generated publication metadata. The kit README",
              "explains each archive and checksum; `AFTER_ZENODO.md`, where present, records the",
              "external deposit and the follow-up required after a future publication.", "",
              "Do not add manuscript mirrors, scratch experiments, or obsolete editions here.",
              "Earlier editions and removed review copies remain recoverable from Git.", ""]
    return "\n".join(lines)


def check_inventory(root: Path) -> None:
    base = root / "preprints"
    expected = expected_files(root)
    actual = {p.relative_to(base).as_posix() for p in base.rglob("*") if p.is_file()}
    if actual != expected:
        raise ValueError(f"Preprint inventory: missing={sorted(expected - actual)}, "
                         f"unowned={sorted(actual - expected)}")
    if (base / "README.md").read_text(encoding="utf-8") != index_text(root):
        raise ValueError("Stale preprint index; run python tools/preprints.py --write-index")
    if (root / "juggler_review").exists():
        raise ValueError("Obsolete juggler_review directory; use preprints")


def check(root: Path) -> None:
    check_inventory(root)
    for letter in (*LETTERS, "a_kit", "b_kit"):
        builder(root, letter).check(root)
    print(f"Preprints: {len(expected_files(root))} owned files; all five releases and kits current.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write-index", action="store_true")
    args = parser.parse_args()
    if args.write_index:
        (ROOT / "preprints/README.md").write_text(index_text(ROOT), encoding="utf-8", newline="\n")
    else:
        check(ROOT)


if __name__ == "__main__":
    main()
