"""Index and validate the current preprints and their publication kits.

Run --write-index after changing a paper's metadata; --check also validates
every release manifest, PDF alias, source archive and kit checksum.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_paper import Paper, letters  # noqa: E402


def expected_files(root: Path) -> set[str]:
    """The index, each paper's PDF and its kit: the same files for every paper."""
    names = {"README.md"}
    for letter in letters(root):
        paper = Paper(letter, root)
        for name in [paper.PDF, *paper.kit_files()]:
            names.add(Path(name).relative_to("preprints").as_posix())
    return names


def index_text(root: Path) -> str:
    lines = [
        "# Preprints", "",
        "Current local papers of the Juggler–Collatz Mathematical Laboratory.",
        "Manuscripts, proof reviews and build instructions live in `docs/theory/`.",
        "This directory holds built PDFs and the files needed to prepare their publication.",
        "Local versions may be ahead of the [recorded deposits](../docs/theory/paper_deposits.md).",
        "A successful build does not publish anything or change a paper's evidence status.", "",
        "<!-- Generated by python tools/preprints.py --write-index. -->", "",
        "| Paper | Local version | PDF | Canonical source | Build guide | Publication kit |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for letter in letters(root):
        paper = Paper(letter, root)
        meta = json.loads((root / paper.METADATA).read_text(encoding="utf-8"))
        stem = paper.STEM
        title = meta["title"].replace("|", "\\|")
        lines.append(f"| {letter.upper()} | {meta['version']} | [{title}]({stem}.pdf) | "
                     f"[Manuscript](../docs/theory/{stem}.md) | "
                     f"[Build](../docs/theory/PAPER_{letter.upper()}_BUILD.md) | "
                     f"[Files and instructions](zenodo_paper_{letter}/README.md) |")
    lines += ["", "## Keeping this directory current", "",
              "Run these commands from the repository root:", "", "```text",
              "python tools/preprints.py --write-index",
              "python tools/preprints.py --check", "```", "",
              "The check rejects missing or unowned files, an outdated index, stale release inputs,",
              "mismatched PDF aliases, and stale archives or checksums. Rebuild an affected paper",
              "using its build guide; never repair a release by editing recorded hashes.", "",
              "Every paper is built by `python tools/build_paper.py <letter>` from its settings in",
              "`tools/papers/`. Every kit holds the same files: the PDF under its upload name, the",
              "source archive `paper_<letter>_sources.zip`, `ZENODO_FIELDS.txt` for the upload form,",
              "`SHA256SUMS.txt`, a README and `AFTER_ZENODO.md`, the record of the deposits. Upload",
              "the PDF and the source archive.", "",
              "Do not add manuscript mirrors, scratch experiments, or obsolete editions here.",
              "Earlier editions and removed review copies remain recoverable from Git.", ""]
    return "\n".join(lines)


def check_inventory(root: Path) -> None:
    base = root / "preprints"
    expected = expected_files(root)
    actual = {p.relative_to(base).as_posix() for p in base.rglob("*") if p.is_file()}
    if actual != expected:
        raise ValueError(f"Preprint inventory: missing={sorted(expected - actual)}, "
                         f"unowned={sorted(actual - expected)}")
    if (base / "README.md").read_text(encoding="utf-8") != index_text(root):
        raise ValueError("Stale preprint index; run python tools/preprints.py --write-index")
    if (root / "juggler_review").exists():
        raise ValueError("Obsolete juggler_review directory; use preprints")


def check(root: Path) -> None:
    check_inventory(root)
    for letter in letters(root):
        Paper(letter, root).check(root)
    print(f"Preprints: {len(expected_files(root))} owned files; all five releases and kits current.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write-index", action="store_true")
    args = parser.parse_args()
    if args.write_index:
        (ROOT / "preprints/README.md").write_text(index_text(ROOT), encoding="utf-8", newline="\n")
    else:
        check(ROOT)


if __name__ == "__main__":
    main()
