"""Render the combined JSON and Markdown ledger from canonical topic claims.

Both aggregate views are generated. Edit docs/claims/<programme>/<topic>.json, then run this script.
Pass --check to fail if either generated view is stale (CI).
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from research.claims import TAGS, load_claims, render_json
from research.claim_dependencies import validate as validate_dependencies

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "docs" / "theory" / "theorem_ledger.json"
MD_PATH = ROOT / "docs" / "theory" / "theorem_ledger.md"

HEADER = """# Theorem ledger

Generated from [canonical topic claims](../claims/README.md).
Machine-readable sibling: [theorem_ledger.json](theorem_ledger.json).

This file is generated by `tools/render_theorem_ledger.py`. Edit the canonical topic JSON files.

Tags:

- `EXACT — LEAN VERIFIED`
- `EXACT — HUMAN PROOF`
- `COMPUTATIONALLY VERIFIED`
- `CONJECTURE`
- `OBSERVATION`
- `REFUTED`
- `REPARAMETERIZATION`

Provenance is copied from the mathematical record and Lean sources.
This ledger does not rewrite history.

| ID | Tag | Statement (short) | Source | Lean | Tests |
|----|-----|-------------------|--------|------|-------|
"""


def _short_lean(path: str) -> str:
    if not path:
        return ""
    return path.removeprefix("formal/").removesuffix(".lean")


def _short_tests(paths: list[str], evidence: str = "") -> str:
    """Test stems, or the declared reason a row has none.

    A blank cell read as "nobody wired this up" whether or not that was true. A row whose
    evidence is a reading of a primary source says so instead; the parentheses keep it from
    reading as a filename.
    """
    if not paths and evidence:
        return f"({evidence})"
    names = []
    for p in paths:
        names.append(Path(p).stem)
    return ", ".join(names)


def check_tags(entries: list[dict]) -> list[str]:
    """Return one message per row whose tag is outside the fixed vocabulary."""
    return [
        f"{row.get('id')}: unknown tag {row.get('tag')!r}"
        for row in entries
        if row.get("tag") not in TAGS
    ]


def render(entries: list[dict], *, root: Path = ROOT) -> str:
    bad = check_tags(entries) + validate_dependencies(entries, root)
    if bad:
        raise ValueError(
            "theorem_ledger.json has invalid evidence tags or proof dependencies:\n  " + "\n  ".join(bad)
        )
    lines = [HEADER]
    for row in entries:
        tests = _short_tests(list(row.get("tests") or []), str(row.get("evidence") or ""))
        lean = _short_lean(str(row.get("lean") or ""))
        # Statements are plain text; iterate notation such as J^[j](n) is not a link.
        statement = str(row.get("statement") or "").replace("|", "\\|").replace("](", "]&#40;")
        source = str(row.get("source") or "")
        lines.append(
            f"| {row['id']} | {row['tag']} | {statement} | {source} | {lean} | {tests} |\n"
        )
    annotated = [row for row in entries if row.get('proof_routes')]
    if annotated:
        lines += ['\n## Recorded proof routes\n\n',
                  'These are written-proof annotations, not additional proof certificates. '
                  'Rows absent from this table have unknown dependency coverage. '
                  'Use `python tools/formalpedia.py claim-graph <ID>` for the selected route and review boundary.\n\n',
                  '| Claim | Route | Immediate coverage | Uses (kind) |\n',
                  '|---|---|---|---|\n']
        for row in annotated:
            for route in row['proof_routes']:
                uses = ', '.join(f"{e['claim']} ({e['kind']})" for e in route['uses'])
                if not uses:
                    uses = 'reviewed empty list' if route['coverage'] == 'complete' else 'none recorded'
                lines.append(f"| {row['id']} | {route['id']} | {route['coverage']} | {uses} |\n")
    return "".join(lines)


def load_entries() -> list[dict]:
    return load_claims(ROOT, check_sources=True).entries


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if either generated aggregate differs from canonical topic claims",
    )
    args = parser.parse_args(argv)
    entries = load_entries()
    text = render(entries, root=ROOT)
    aggregate = render_json(entries)
    if args.check:
        current = MD_PATH.read_text(encoding="utf-8") if MD_PATH.exists() else ""
        current_json = JSON_PATH.read_text(encoding="utf-8") if JSON_PATH.exists() else ""
        if current != text or current_json != aggregate:
            print("Generated claim aggregates are stale; run tools/render_theorem_ledger.py")
            return 1
        return 0
    JSON_PATH.write_text(aggregate, encoding="utf-8", newline="\n")
    MD_PATH.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
